---
title: 'Wrangling'
format: html
editor: visual
---

```{r Notes}


## Columns ##

# Nest_ID: the trapnest number, cavity number, and straw ID put together 
# Index: every row as a unique number that I needed for a loop
# Status: the activity of that cavity, e.g., its empty, new cells are made, a nest is sealed off, etc.
# Bee_choice: is a new nest built or not, Yes = 1, no = 0, pseudo nests or nests already in progress or completed get an NA.
# Available_post: number of available cavities for each trapnest and date combo AFTER the new nests for that visit have been started (i.e., how many available cavities that the experiments saw when arriving to the nest)
# New_nests_os: number of new osmia nests for each trapnest and date combo
# New_nests_meg: number of new megachile nests for each trapnest and date combo

# Osmia_ps_prior: the average number of osmia in each trapnest per date, prior to the number of new nests built that day, including pseudo nests
# Osmia_no_ps_prior: the average number of osmia in each trapnest per date, prior to the number of new nests built that day, excluding pseudo nests
# Meg_ps_prior: the average number of megachile in each trapnest per date, prior to the number of new nests built that day, including pseudo nests
# Meg_no_ps_prior: the average number of megachile in each trapnest per date, prior to the number of new nests built that day, excluding pseudo nests

# Osmia_ps_no_iw: the number of osmia in each trapnest per date, including new nests built that day, including pseudo nests, excluding only inner walls, for the parasite models (e.g., counting nests that a parasite could have infected)
# Osmia_no_ps_no_iw: the number of osmia in each trapnest per date, including new nests built that day, excluding pseudo nests, excluding only inner walls, for the parasite models
# Meg_ps_no_iw: the number of megachile in each trapnest per date, including new nests built that day, including pseudo nests, excluding only inner walls, for the parasite models
# Meg_no_ps_no_iw: the number of megachile in each trapnest per date, including new nests built that day, excluding pseudo nests, excluding only inner walls, for the parasite models

# New_nests_sum: total number of new nests including megachile and osmia.
# Available_cavities_prior: The number of cavities that were available for bees to nest in. E.g., if there are 2 new nests in a low-occupancy treatment, then there were 18 Available_cavities_prior, 2 new nests, and now 16 Available_post
# Available_post = Osmia_ps_prior + Meg_ps_prior (+ non-target nests) = 18

# Sum_unsealed can have NAs for when parasites are present


```

```{r Cleaning_2023}

knitr::opts_chunk$set(echo = TRUE) 
library(tidyverse)

# Load data
data_2023 <- read_csv('Data/Aggregate_nesting_data_2023.csv')

## Add in straws that remained empty throughout the experiment

# add empty data frame
empty_data_2023 <- read_csv('Data/Empty_data_2023.csv')
# add columns to say 'for binding' or NA to tell data frames apart and prioritize the collected data
empty_data_2023$For_binding <- 0
data_2023$For_binding <- 1
# merge data frames
data_2023 <- bind_rows(empty_data_2023, data_2023)
# make nest ID column
data_2023$Nest_ID <- with(data_2023, paste(Trapnest, paste0(Cavity_number, Straw_ID), sep = '_'))
# make cavity ID column
data_2023$Cavity_ID <- with(data_2023, paste(Trapnest, Cavity_number, sep = '_'))
# make Trapnest a character
data_2023$Trapnest <- paste('trapnest', data_2023$Trapnest, sep = '_')

# to delete duplicate rows, check if it adds up
length(empty_data_2023$Straw_ID) # 1295 (minus one for the header)
# length(data_2023$Straw_ID) data when first reading is 1113 (minus header)
sum(duplicated(data_2023$Nest_ID)) # 701 duplicates
data_2023 <- data_2023 %>%
  group_by(Nest_ID) %>%
  filter(For_binding == max(For_binding))
length(data_2023$Nest_ID) 

# pivot longer and inspect
long_data_2023 <- pivot_longer(data_2023, '06-May':'09-Aug', names_to = 'Date', values_to = 'Status')
table(long_data_2023$Status)
table(long_data_2023$Occupant)

## Make the date column actually a date

# divide Date column from day-month into two columns
long_data_2023 <- long_data_2023 %>%
  separate(Date, c('day', 'month'))
# inspect
table(long_data_2023$day)
table(long_data_2023$month)
# replace month names
long_data_2023$month <- replace(long_data_2023$month, long_data_2023$month == 'Jun', 'June')
long_data_2023$month <- replace(long_data_2023$month, long_data_2023$month == 'Aug', 'August')
long_data_2023$month <- replace(long_data_2023$month, long_data_2023$month == 'Jul', 'July')
# make new column with months as numbers
long_data_2023$month2 <- match(long_data_2023$month, month.name)
# add column for the year
long_data_2023 <- long_data_2023 %>% mutate(Year = 2023)
# make a column with the full date that is read by R as a date
long_data_2023$Date <- as.Date(with(long_data_2023, paste(Year, month2, day, sep = '-')), '%Y-%m-%d')
# check if R recognizes it as a date
str(long_data_2023)

## Inner wall only

# get names of nests that had inner wall started before making those empty, will be useful for later
inner_wall_started_2023_1 <- long_data_2023 %>%
  filter(Status == 'inner wall started') %>%
  distinct(Nest_ID, .keep_all = TRUE) # might contain nests that eventually had cells, check in chunk Inner_Wall_Only 

# how many were eaten in 2023?
long_data_2023 %>% filter(Status == 'eaten') # 5

# Replace some input for statuses of how they should be treated
long_data_2023$Status <- replace(long_data_2023$Status, long_data_2023$Status == 'eaten', 'empty')
long_data_2023$Status <- replace(long_data_2023$Status, long_data_2023$Status == 'inner wall started', 'empty')
long_data_2023$Status <- replace(long_data_2023$Status, long_data_2023$Status == 'non-target inner wall started', 'empty') # all of the statuses after the initial 'inner wall started' are still 'inner wall started' as opposed to 'no change', in the raw data 


## Fixing the Occupant column

# at first, this column says the occupant for the entire data collection period, even if the nest if empty for most of it
# make a new column, needs to ne 'NA' of loop wont run
long_data_2023 <- long_data_2023 %>% mutate(Occupant.v2 = if_else(Status == 'non_existent', 'NA', if_else(Status == 'empty', 'none', Occupant)))
long_data_2023 <- long_data_2023 %>% mutate(Occupant.v3 = if_else(Status == 'no_visit', 'NA', Occupant.v2))
# add occupant for pseudo nests, Osmia first half of summer, Megachile second half
long_os <- long_data_2023 %>%
  filter(Site == 'NN' | Subsite == 'A' | Subsite == 'B' | Subsite == 'C' | Subsite == 'D' | Subsite == 'E' | Subsite == 'F') %>%
  mutate(Occupant.v3 = if_else(Status == 'pseudo', 'osmia', Occupant.v3))
# add megachile for pseudo nest type
long_meg <- long_data_2023 %>%
  filter(Site == 'CP' | Subsite == 'M' | Subsite == 'N' | Subsite == 'O' | Subsite == 'P' | Subsite == 'Q' | Subsite == 'R') %>%
  mutate(Occupant.v3 = if_else(Status == 'pseudo', 'megachile', Occupant.v3))
# merge back together
long_data_2023 <- rbind(long_os, long_meg)
# Take columns that I want
long_data_2023 <- long_data_2023 %>% select(Site:Straw_ID, Straw_length_mm, Filled_length_mm, Nest_ID, Cavity_ID, Occupant.v3, Date, Status)
# rename new occupant.v2 column
long_data_2023 <- rename(long_data_2023, Occupant = Occupant.v3)

# check if each trapnest has 18 existing cavities (unique cavity IDs) for each visit
long_data_2023 %>%
  filter(Status != 'non_existent' & Status != 'no_visit') %>%
  group_by(Trapnest, Date) %>%
  summarize(Count = length(unique(Nest_ID)))

# remove chunks of 'non_existent' for first and second half of the summer so the loop runs faster
# for the first half of the summer, BP and NN had different chunks of non_existents, so there's separate lists of data for them. But for the second half, CP and BP had the same dates so there's one list
long_data_BP_2023 <- long_data_2023 %>% filter(Subsite == 'A' | Subsite == 'B' | Subsite == 'C' | Subsite == 'D' | Subsite == 'E' | Subsite == 'F')
long_data_NN_2023 <- long_data_2023 %>% filter(Subsite == 'G' | Subsite == 'H' | Subsite == 'I' | Subsite == 'J' | Subsite == 'K' | Subsite == 'L')
long_data_BP_2023 <- long_data_BP_2023 %>% filter(Date != '2023-05-06' & Date != '2023-06-30' & Date != '2023-07-03' & Date != '2023-07-04' & Date != '2023-07-05' & Date != '2023-07-06' & Date != '2023-07-07' & Date != '2023-07-10' & Date != '2023-07-12' & Date != '2023-07-14' & Date != '2023-07-17' & Date != '2023-07-20' & Date != '2023-07-24' & Date != '2023-07-26' & Date != '2023-07-28' & Date != '2023-07-29' & Date != '2023-08-01' & Date != '2023-08-04' & Date != '2023-08-09')
long_data_NN_2023 <- long_data_NN_2023 %>% filter(Date != '2023-07-07' & Date != '2023-07-10' & Date != '2023-07-12' & Date != '2023-07-14' & Date != '2023-07-17' & Date != '2023-07-20' & Date != '2023-07-24' & Date != '2023-07-26' & Date != '2023-07-28' & Date != '2023-07-29' & Date != '2023-08-01' & Date != '2023-08-04' & Date != '2023-08-09')
long_data_second_2023 <- long_data_2023 %>% filter(Subsite == 'M' | Subsite == 'N' | Subsite == 'O' | Subsite == 'P' | Subsite == 'Q' | Subsite == 'R' | Subsite == 'S' | Subsite == 'T' | Subsite == 'U' | Subsite == 'V' | Subsite == 'W' | Subsite == 'X')
long_data_second_2023 <- long_data_second_2023 %>% filter(Date != '2023-05-06' & Date != '2023-05-07' & Date != '2023-05-11' & Date != '2023-05-12' & Date != '2023-05-15' & Date != '2023-05-16' & Date != '2023-05-17' & Date != '2023-05-18' & Date != '2023-05-19' & Date != '2023-05-21' & Date != '2023-05-22' & Date != '2023-05-23' & Date != '2023-05-25' & Date != '2023-05-26' & Date != '2023-05-28' & Date != '2023-05-29' & Date != '2023-05-31' & Date != '2023-06-01' & Date != '2023-06-02' & Date != '2023-06-04' & Date != '2023-06-05' & Date != '2023-06-08' & Date != '2023-06-09' & Date != '2023-06-10' & Date != '2023-06-11' & Date != '2023-06-12' & Date != '2023-06-14' & Date != '2023-06-15' & Date != '2023-06-16' & Date != '2023-06-19' & Date != '2023-06-20' & Date != '2023-06-22' & Date != '2023-06-23' & Date != '2023-06-29' & Date != '2023-06-30')

long_data_2023 <- rbind(long_data_BP_2023, long_data_NN_2023, long_data_second_2023) # 15180 + 18486 + 13124 = 46790


## Loop for making the column for new nests per visit at the cavity-level

# make an index
index_2023 <- (1:length(long_data_2023$Site)) # make index of 1 to last row
long_i_2023 <- long_data_2023
long_i_2023$index <- index_2023 # making index column to count
long_i_2023 <- long_i_2023 %>% relocate('index') # puts it in the front
# initialize a table for bee choice
Bee_choice_2023 <- as.data.frame(matrix(NA,0,2))
colnames(Bee_choice_2023)[1] <- 'index'
colnames(Bee_choice_2023)[2]<-'Bee_choice'
# saying for i in each of the rows in index

### START
for (i in long_i_2023$index) { 
  # make an i-1 and i-2 and i-3 variable
  i_status <- long_i_2023$Status[i]
  i_minus_one_status <- long_i_2023$Status[i-1]
  i_minus_two_status <- long_i_2023$Status[i-2]
  i_minus_three_status <- long_i_2023$Status[i-3]
  # initialize a choice variable
  choice <- 'blank'
  
  if(i_status == 'non_existent' | i_status == 'no change' | i_status == 'no_visit' | i_status == 'pseudo') {
    choice <- 'NA'
  }else{
    if(i_status == 'empty'){
      choice <- '0'
      }else{
        if(i_status != 'non_existent' & i_status != 'no change' & i_status != 'no_visit' & i_status != 'pseudo' & i_status != 'empty' & i_minus_one_status == 'non_existent' | i_minus_one_status == 'empty') {
        choice <- '1'
      }else{
        if(i_status != 'non_existent' & i_status != 'no change' & i_status != 'no_visit' & i_status != 'pseudo' & i_status != 'empty' & i_minus_one_status == 'no_visit' & i_minus_two_status == 'non_existent' | i_minus_two_status == 'empty') {
          choice <- '1'
        }else{ 
          if(i_status != 'non_existent' & i_status != 'no change' & i_status != 'no_visit' & i_status != 'pseudo' & i_status != 'empty' & i_minus_one_status != 'non_existent' | i_minus_one_status != 'empty') {
          choice <- 'NA' 
          }else{
            if(i_status != 'non_existent' & i_status != 'no change' & i_status != 'no_visit' & i_status != 'pseudo' & i_status != 'empty' & i_minus_one_status == 'no_visit' & i_minus_two_status != 'non_existent' & i_minus_two_status != 'empty') {
            choice <- 'NA'
            }else{ 
              if(i_status != 'non_existent' & i_status != 'no change' & i_status != 'no_visit' & i_status != 'pseudo' & i_status != 'empty' & i_minus_one_status == 'no_visit' & i_minus_two_status == 'no_visit' & i_minus_three_status != 'non_existent' & i_minus_three_status != 'empty') {choice <- 'leftover'}
              else{ 
                choice <- 'leftover'}
      }}}}}}

  occupant_i <- long_i_2023$Occupant[i]
  if(occupant_i == 'wasp' | occupant_i == 'hylaeus' | occupant_i == 'resin bee' | occupant_i == 'heriades' | occupant_i == 'hoplitis'){
    choice <- 'NA'
  } else {choice <- choice}

  # create Bee_choice row for our big table
  Bee_choice_i <- as.data.frame(matrix(NA,0,2))
  colnames(Bee_choice_i)[1] <- 'index'
  colnames(Bee_choice_i)[2] <- 'Bee_choice'
  Bee_choice_i[nrow(Bee_choice_i)+1,] = c(i,choice)
  # bind the row to the big table
  Bee_choice_2023 <- rbind(Bee_choice_2023, Bee_choice_i)
} ### END

# Join products together
Bee_choice_2023$index <- as.numeric(Bee_choice_2023$index)
long_choice_2023 <- long_i_2023 %>% left_join(Bee_choice_2023)
long_choice_2023$Bee_choice <- as.numeric(long_choice_2023$Bee_choice)

# Inspect new nests
sum(long_choice_2023$Bee_choice, na.rm = TRUE) # 264 new nests, but this is incorrect, we had fewer nests, are there duplicates?
inspect_2023_new_nest <- long_choice_2023 %>% filter(Bee_choice == 1)
# some duplicates, like 5_9a, 6_17a, 7_3a, 29_1b
length(unique(inspect_2023_new_nest$Nest_ID)) # 226 unique nests, that makes more sense
# show the duplicates
inspect_2023_new_nest %>%
  group_by(Nest_ID) %>%
  filter(n() > 1) %>%
  arrange(Nest_ID)
# there does not seem to be a pattern for why these nest are being counted twice in the loop, so manually remove the duplicates
# remove duplicates by arranging by date first, then replace with NA
long_choice_2023 <- long_choice_2023 %>%
  arrange(Nest_ID, Date) %>% 
  group_by(Nest_ID) %>%
  mutate(Bee_choice = if_else(
    Bee_choice == 1 & duplicated(Bee_choice == 1), 
    NA, 
    Bee_choice)) %>%
  ungroup()
# check the sum
sum(long_choice_2023$Bee_choice, na.rm = TRUE) 
# 226, perfect

table(long_choice_2023$Occupant[long_choice_2023$Bee_choice == 1])


```

```{r Cleaning_2024}
 

## Load data
data_2024 <- read_csv('Data/Aggregate_nesting_data_2024.csv')

# make nest ID column
data_2024$Nest_ID <- with(data_2024, paste(Trapnest, paste0(Cavity_number, Straw_ID), sep = '_'))
# make cavity ID column
data_2024$Cavity_ID <- with(data_2024, paste(Trapnest, Cavity_number, sep = '_'))
# make Trapnest a character
data_2024$Trapnest <- paste('trapnest', data_2024$Trapnest, sep = '_')

## Pivot longer and inspect
long_data_2024 <- pivot_longer(data_2024, '05-Jun':'13-Aug', names_to = 'Date', values_to = 'Status')
table(long_data_2024$Status) 
table(long_data_2024$Occupant) 


## Make the date column actually a date

# divide Date column from day-month into two columns
long_data_2024 <- long_data_2024 %>% 
  separate(Date, c('day', 'month')) 
# inspect
table(long_data_2024$day)
table(long_data_2024$month)
# replace month names
long_data_2024$month <- replace(long_data_2024$month, long_data_2024$month == 'Jun','June')
long_data_2024$month <- replace(long_data_2024$month, long_data_2024$month == 'Jul', 'July')
long_data_2024$month <- replace(long_data_2024$month, long_data_2024$month == 'Aug', 'August')
# make new column with months as numbers
long_data_2024$month2 <- match(long_data_2024$month, month.name) 
# add column for the year
long_data_2024 <- long_data_2024 %>% mutate(Year = 2024)
# make a column with the full date that is read by R as a date
long_data_2024$Date <- as.Date(with(long_data_2024, paste(Year, month2, day,sep='-')), '%Y-%m-%d')
# check if R recognizes it as a date
str(long_data_2024)

# get names of nests that had inner wall started before making those empty, will be useful for later
inner_wall_started_2024_1 <- long_data_2024 %>%
  filter(Status == 'inner wall started') %>%
  distinct(Nest_ID, .keep_all = TRUE) # might contain nests that eventually had cells

# replace some input for statuses of how they should be treated
long_data_2024$Status <- replace(long_data_2024$Status, long_data_2024$Status=='eaten','empty')
long_data_2024$Status <- replace(long_data_2024$Status, long_data_2024$Status=='inner wall started','empty') # all of the statuses after the initial 'inner wall started' are still 'inner wall started' as opposed to 'no change', in the raw data 
long_data_2024$Status <- replace(long_data_2024$Status, long_data_2024$Status=='non-target inner wall started','empty')
long_data_2024$Status <- replace(long_data_2024$Status, long_data_2024$Status=='activity','no change') # meant there was some new material in the nest but didn't change the overall status (e.g., more pollen added to the same cell as last time)
long_data_2024$Status <- replace(long_data_2024$Status, long_data_2024$Status=='end chewed','empty') # megachile would chew the ends of the straws, so we would replace them with new ones


## Fixing the Occupant column

# at first, this column says the occupant for the entire data collection period, even if the nest if empty for most of it
# make a new column, needs to ne 'NA' of loop wont run
long_data_2024 <- long_data_2024 %>% mutate(Occupant.v2 = if_else(Status == 'non_existent', 'NA', if_else(Status == 'empty', 'none', Occupant)))
long_data_2024 <- long_data_2024 %>% mutate(Occupant.v3 = if_else(Status == 'no_visit', 'NA', Occupant.v2))
# add occupant for pseudo nests, all Megachile 
long_data_2024 <- long_data_2024 %>%  
  mutate(Occupant.v3 = if_else(Status == 'pseudo', 'megachile', Occupant.v3))
# Take columns that I want
long_data_2024 <- long_data_2024 %>% select(Site:Straw_ID, Straw_length_mm, Filled_length_mm, Nest_ID, Cavity_ID, Occupant.v3, Date, Status)
# rename new occupant.v2 column
long_data_2024 <- rename(long_data_2024, Occupant = Occupant.v3)

# check if each trapnest has 18 existing cavities (unique cavity IDs) for each visit
long_data_2024 %>% 
  filter(Status != 'non_existent' & Status != 'no_visit') %>% 
  group_by(Trapnest, Date) %>% 
  summarize(Count = length(unique(Nest_ID))) 


## Loop for making the column for new nests per visit at the cavity-level

# change all NAs to the character 'NA'
long_data_2024$Occupant[is.na(long_data_2024$Occupant)] <- 'NA'

# make an index
index_2024 <- (1:length(long_data_2024$Site)) # make index of 1 to last row
long_i_2024 <- long_data_2024
long_i_2024$index <- index_2024 # making index column to count
long_i_2024 <- long_i_2024 %>% relocate('index') # puts it in the front
# initialize a table for bee choice
Bee_choice_2024 <- as.data.frame(matrix(NA,0,2))
colnames(Bee_choice_2024)[1] <- 'index'
colnames(Bee_choice_2024)[2]<-'Bee_choice'
# saying for i in each of the rows in index

### START
for (i in long_i_2024$index) { 
  # make an i-1 and i-2 and i-3 variable
  i_status <- long_i_2024$Status[i]
  i_minus_one_status <- long_i_2024$Status[i-1]
  i_minus_two_status <- long_i_2024$Status[i-2]
  i_minus_three_status <- long_i_2024$Status[i-3]
  # initialize a choice variable
  choice <- 'blank'
  
  if(i_status == 'non_existent' | i_status == 'no change' | i_status == 'no_visit' | i_status == 'pseudo') {
    choice <- 'NA'
  }else{
    if(i_status == 'empty'){
      choice <- '0'
      }else{
        if(i_status != 'non_existent' & i_status != 'no change' & i_status != 'no_visit' & i_status != 'pseudo' & i_status != 'empty' & i_minus_one_status == 'non_existent' | i_minus_one_status == 'empty') {
        choice <- '1'
      }else{
        if(i_status != 'non_existent' & i_status != 'no change' & i_status != 'no_visit' & i_status != 'pseudo' & i_status != 'empty' & i_minus_one_status == 'no_visit' & i_minus_two_status == 'non_existent' | i_minus_two_status == 'empty') {
          choice <- '1'
        }else{ 
          if(i_status != 'non_existent' & i_status != 'no change' & i_status != 'no_visit' & i_status != 'pseudo' & i_status != 'empty' & i_minus_one_status != 'non_existent' | i_minus_one_status != 'empty') {
          choice <- 'NA' 
          }else{
            if(i_status != 'non_existent' & i_status != 'no change' & i_status != 'no_visit' & i_status != 'pseudo' & i_status != 'empty' & i_minus_one_status == 'no_visit' & i_minus_two_status != 'non_existent' & i_minus_two_status != 'empty') {
            choice <- 'NA'
            }else{ 
              if(i_status != 'non_existent' & i_status != 'no change' & i_status != 'no_visit' & i_status != 'pseudo' & i_status != 'empty' & i_minus_one_status == 'no_visit' & i_minus_two_status == 'no_visit' & i_minus_three_status != 'non_existent' & i_minus_three_status != 'empty') {choice <- 'leftover'}
              else{ 
                choice <- 'leftover'}
      }}}}}}

  occupant_i <- long_i_2024$Occupant[i]
  if(occupant_i == 'wasp' | occupant_i == 'hylaeus' | occupant_i == 'resin bee' | occupant_i == 'heriades' | occupant_i == 'hoplitis' | occupant_i == 'non-target bee'){
    choice <- 'NA'
  } else {choice <- choice}

  # create Bee_choice row for our big table
  Bee_choice_i <- as.data.frame(matrix(NA,0,2))
  colnames(Bee_choice_i)[1] <- 'index'
  colnames(Bee_choice_i)[2] <- 'Bee_choice'
  Bee_choice_i[nrow(Bee_choice_i)+1,] = c(i,choice)
  # bind the row to the big table
  Bee_choice_2024 <- rbind(Bee_choice_2024, Bee_choice_i)
} ### END

# Join products together
Bee_choice_2024$index <- as.numeric(Bee_choice_2024$index)
long_choice_2024 <- long_i_2024 %>% left_join(Bee_choice_2024)
long_choice_2024$Bee_choice <- as.numeric(long_choice_2024$Bee_choice)

# Inspect new nests
sum(long_choice_2024$Bee_choice, na.rm = TRUE)  # 118 new nests, any duplicates?
inspect_2024_new_nest <- long_choice_2024 %>% filter(Bee_choice == 1)
# some duplicates, like 100_10a, 102_12a, 104_7a
length(unique(inspect_2024_new_nest$Nest_ID)) # 81 new nests unique nests
# show the duplicates
inspect_2024_new_nest %>%
  group_by(Nest_ID) %>%
  filter(n() > 1) %>%
  arrange(Nest_ID)
# there does not seem to be a pattern for why these nest are being counted twice in the loop, so manually remove the duplicates
# remove duplicates by arranging by date first, then replace with NA
long_choice_2024 <- long_choice_2024 %>%
  arrange(Nest_ID, Date) %>% 
  group_by(Nest_ID) %>%
  mutate(Bee_choice = if_else(
    Bee_choice == 1 & duplicated(Bee_choice == 1), 
    NA, 
    Bee_choice)) %>%
  ungroup()
# check the sum
sum(long_choice_2024$Bee_choice, na.rm = TRUE) 
# check only megachile and osmia have new nests counted
table(long_choice_2024$Occupant[long_choice_2024$Bee_choice == 1])


```

```{r Nests_Containing_Cells_2023}
 

## Categorize occupied nests as containing cells, or as just inner walls

# make column to say if the Status contains the word 'cell' (1) or not (0)
contains_cells_2023 <- long_choice_2023 %>% filter(Status != 'empty' & Status != 'pseudo' & Occupant == 'osmia' | Status != 'empty' & Status != 'pseudo' & Occupant == 'megachile')
contains_cells_2023$Contains_cells_bin <- if_else(grepl('cell', contains_cells_2023$Status), 1, 0) 

## Loop to say nests contained cells for the duration they remained in the trapnest

# arrange data chronologically
contains_cells_2023 <- contains_cells_2023 %>% arrange(Nest_ID, Date)
# initiate new column, then fill it in
contains_cells_2023$Contains_cells_cumulative <- contains_cells_2023$Contains_cells_bin 

### START
for(i in 1:nrow(contains_cells_2023)){
  nestID <- contains_cells_2023$Nest_ID[i] # focal nest for i-th row
  dt <- contains_cells_2023$Date[i] # date for i-th row
  allprev <- contains_cells_2023 %>% filter(Nest_ID == nestID & Date <= dt) %>% pull(Contains_cells_cumulative) #  previous counts for that focal nest
  
  check1 <- !all(is.na(allprev))

  if(check1){
    contains_cells_2023$Contains_cells_cumulative[i] <- max(allprev, na.rm = T)
  }
} ### END

# remove unnecessary columns
contains_cells_2023 <- contains_cells_2023 %>% select(-Contains_cells_bin)
# rename column and df
contains_cells_2023 <- contains_cells_2023 %>% rename(Contains_cells = Contains_cells_cumulative)

# merge with prefs
long_choice_2023 <- full_join(long_choice_2023, contains_cells_2023)
long_choice_2023 <- long_choice_2023 %>% arrange(Nest_ID, Date)

```

```{r Nests_Containing_Cells_2024}


## Categorize occupied nests as containing cells, or as just inner walls
 
# make column to say if the Status contains the word 'cell' (1) or not (0)
contains_cells_2024 <- long_choice_2024 %>% filter(Status != 'empty' & Status != 'pseudo' & Occupant == 'osmia' | Status != 'empty' & Status != 'pseudo' & Occupant == 'megachile')
contains_cells_2024$Contains_cells_bin <- if_else(grepl('cell', contains_cells_2024$Status), 1, 0) 


## Loop to say nests contained cells for the duration they remained in the trapnest

# arrange data chronologically
contains_cells_2024 <- contains_cells_2024 %>% arrange(Nest_ID, Date)
# initiate new column, then fill it in
contains_cells_2024$Contains_cells_cumulative <- contains_cells_2024$Contains_cells_bin 

### START
for(i in 1:nrow(contains_cells_2024)){
  nestID <- contains_cells_2024$Nest_ID[i] # focal nest for i-th row
  dt <- contains_cells_2024$Date[i] # date for i-th row
  allprev <- contains_cells_2024 %>% filter(Nest_ID == nestID & Date <= dt) %>% pull(Contains_cells_cumulative) #  previous counts for that focal nest
  
  check1 <- !all(is.na(allprev))

  if(check1){
    contains_cells_2024$Contains_cells_cumulative[i] <- max(allprev, na.rm = T)
  }
} ### END

# remove unnecessary columns
contains_cells_2024 <- contains_cells_2024 %>% select(-Contains_cells_bin)
# rename column and df
contains_cells_2024 <- contains_cells_2024 %>% rename(Contains_cells = Contains_cells_cumulative)

# merge with prefs
long_choice_2024 <- full_join(long_choice_2024, contains_cells_2024)
long_choice_2024 <- long_choice_2024 %>% arrange(Nest_ID, Date)


```

```{r Available_Cavities_Post_2023}


## Count the number of Available Cavities in each trapnest after the new nests for that visit

# make a new column to say available (1) or not (0), or NA
long_avail_2023 <- long_choice_2023 %>% 
  mutate(Available_bin = if_else(Status == 'no_visit' | Status == 'non_existent', NA, if_else(Status == 'empty', 1,  0))) 
# make a summary column to say the number of available nests in each trapnest by date AFTER that visit's bees began nesting
summ_avail_2023 <- long_avail_2023 %>% 
  group_by(Trapnest, Date) %>% 
  summarize(Available_post = sum(Available_bin, na.rm = T))
# the zeros are no_visits, so replace zeros with NA
summ_avail_2023$Available_post <- replace(summ_avail_2023$Available_post, summ_avail_2023$Available_post == 0, NA)
# Available_post: number of available cavities for each trapnest and date combo after new nests had been built, i.e., the number of available cavities we saw on that visit


```

```{r Available_Cavities_Post_2024}
 

## Count the number of Available Cavities in each trapnest after the new nests for that visit

# make a new column to say available (1) or not (0), or NA
long_avail_2024 <- long_choice_2024 %>% 
  mutate(Available_bin = if_else(Status == 'no_visit' | Status == 'non_existent', NA, if_else(Status == 'empty', 1,  0))) 
# make a summary column to say the number of available nests in each trapnest by date AFTER that visit's bees began nesting
summ_avail_2024 <- long_avail_2024 %>% 
  group_by(Trapnest, Date) %>% 
  summarize(Available_post = sum(Available_bin, na.rm = T))
# the zeros are no_visits, so replace zeros with NA
summ_avail_2024$Available_post <- replace(summ_avail_2024$Available_post, summ_avail_2024$Available_post == 0, NA)
# Available_post: number of available cavities for each trapnest and date combo after new nests had been built, i.e., the number of available cavities we saw on that visit


```

```{r Conspecific_Presence_2023}
 

# includes inner walls only as conspecifics

## Nesting according to conspecific presence (with and without pseudo nests) ##

## Osmia ##

# Make column to say osmia present or not, including pseudo
conspecifics_os_2023 <- long_choice_2023 %>% 
  mutate(Osmia_bi_ps = if_else(Occupant == 'osmia', 1, 0))  

# Make column to say osmia present or not, excluding pseudo
conspecifics_os_2023 <- conspecifics_os_2023 %>% 
  mutate(Osmia_bi_no_ps = if_else(Occupant == 'osmia' & Status != 'pseudo', 1, 0)) 

## Count the number of osmia in each nest

# with pseudo nests/ pseudo nests considered osmia occupancies
summ_osmia_ps_2023 <- conspecifics_os_2023 %>% 
  group_by(Trapnest, Date) %>% 
  summarize(Osmia_ps = (sum(Osmia_bi_ps)))
# Osmia_ps: number of osmia in each trapnest per date, including pseudo nests

# without pseudo nests (pseudo nests not considered osmia occupancies)
summ_osmia_no_ps_2023 <- conspecifics_os_2023 %>% 
  group_by(Trapnest, Date) %>% 
  summarize(Osmia_no_ps = (sum(Osmia_bi_no_ps)))
# Osmia_no_ps: number of osmia in each trapnest per date, excluding pseudo nests

# Merge together
conspecifics_os_2_2023 <- merge(conspecifics_os_2023,  summ_osmia_ps_2023, all.x = TRUE)
conspecifics_os_2_2023 <- merge(conspecifics_os_2_2023,  summ_osmia_no_ps_2023, all.x = TRUE)

# Delete columns I dont need
conspecifics_os_2_2023 <- conspecifics_os_2_2023 %>% select(-Osmia_bi_ps, -Osmia_bi_no_ps )


## Megachile ##

# Make column to say osmia present or not, including pseudo
conspecifics_meg_2023 <- long_choice_2023 %>% 
  mutate(Mega_bi_ps = if_else(Occupant == 'megachile', 1, 0)) 

# Make column to say osmia present or not, excluding pseudo
conspecifics_meg_2023 <- conspecifics_meg_2023 %>% 
  mutate(Mega_bi_no_ps = if_else(Occupant == 'megachile' & Status != 'pseudo', 1, 0)) 

## Count the number of genera in each nest

# with pseudo nests/ pseudo nests considered osmia occupancies
summ_meg_ps_2023 <- conspecifics_meg_2023 %>% 
  group_by(Trapnest, Date) %>% 
  summarize(Meg_ps = (sum(Mega_bi_ps)))
# Meg_ps: number of megachile in each trapnest per date, including pseudo nests

# without pseudo nests/ pseudo nests not considered osmia occupancies
summ_meg_no_ps_2023 <- conspecifics_meg_2023 %>% 
  group_by(Trapnest, Date) %>% 
  summarize(Meg_no_ps = (sum(Mega_bi_no_ps)))
# Meg_no_ps: number of megachile in each trapnest per date, excluding pseudo nests

# Merge together
conspecifics_meg_2_2023 <- merge(conspecifics_meg_2023,  summ_meg_ps_2023, all.x = TRUE)
conspecifics_meg_2_2023 <- merge(conspecifics_meg_2_2023,  summ_meg_no_ps_2023, all.x = TRUE)

# Delete columns I dont need
conspecifics_meg_2_2023 <- conspecifics_meg_2_2023 %>% select(-Mega_bi_ps, -Mega_bi_no_ps )

# Join Osmia and Megachile data together
conspecifics_both_1_2023 <- merge(conspecifics_os_2_2023, conspecifics_meg_2_2023)


```

```{r Conspecific_Presence_2024}
 

# includes inner walls only as conspecifics

## Nesting according to conspecific presence (with and without pseudo nests) ##

## Osmia ##

# Make column to say osmia present or not, including pseudo
conspecifics_os_2024 <- long_choice_2024 %>% 
  mutate(Osmia_bi_ps = if_else(Occupant == 'osmia', 1, 0))  

# Make column to say osmia present or not, excluding pseudo
conspecifics_os_2024 <- conspecifics_os_2024 %>% 
  mutate(Osmia_bi_no_ps = if_else(Occupant == 'osmia' & Status != 'pseudo', 1, 0)) 

## Count the number of osmia in each nest

# with pseudo nests/ pseudo nests considered osmia occupancies
summ_osmia_ps_2024 <- conspecifics_os_2024 %>% 
  group_by(Trapnest, Date) %>% 
  summarize(Osmia_ps = (sum(Osmia_bi_ps)))
# Osmia_ps: number of osmia in each trapnest per date, including pseudo nests

# without pseudo nests (pseudo nests not considered osmia occupancies)
summ_osmia_no_ps_2024 <- conspecifics_os_2024 %>% 
  group_by(Trapnest, Date) %>% 
  summarize(Osmia_no_ps = (sum(Osmia_bi_no_ps)))
# Osmia_no_ps: number of osmia in each trapnest per date, excluding pseudo nests

# Merge together
conspecifics_os_2_2024 <- merge(conspecifics_os_2024,  summ_osmia_ps_2024, all.x = TRUE)
conspecifics_os_2_2024 <- merge(conspecifics_os_2_2024,  summ_osmia_no_ps_2024, all.x = TRUE)

# Delete columns I dont need
conspecifics_os_2_2024 <- conspecifics_os_2_2024 %>% select(-Osmia_bi_ps, -Osmia_bi_no_ps )


## Megachile ##

# Make column to say osmia present or not, including pseudo
conspecifics_meg_2024 <- long_choice_2024 %>% 
  mutate(Mega_bi_ps = if_else(Occupant == 'megachile', 1, 0)) 

# Make column to say osmia present or not, excluding pseudo
conspecifics_meg_2024 <- conspecifics_meg_2024 %>% 
  mutate(Mega_bi_no_ps = if_else(Occupant == 'megachile' & Status != 'pseudo', 1, 0)) 

## Count the number of genera in each nest

# with pseudo nests/ pseudo nests considered osmia occupancies
summ_meg_ps_2024 <- conspecifics_meg_2024 %>% 
  group_by(Trapnest, Date) %>% 
  summarize(Meg_ps = (sum(Mega_bi_ps)))
# Meg_ps: number of megachile in each trapnest per date, including pseudo nests

# without pseudo nests/ pseudo nests not considered osmia occupancies
summ_meg_no_ps_2024 <- conspecifics_meg_2024 %>% 
  group_by(Trapnest, Date) %>% 
  summarize(Meg_no_ps = (sum(Mega_bi_no_ps)))
# Meg_no_ps: number of megachile in each trapnest per date, excluding pseudo nests

# Merge together
conspecifics_meg_2_2024 <- merge(conspecifics_meg_2024,  summ_meg_ps_2024, all.x = TRUE)
conspecifics_meg_2_2024 <- merge(conspecifics_meg_2_2024,  summ_meg_no_ps_2024, all.x = TRUE)

# Delete columns I dont need
conspecifics_meg_2_2024 <- conspecifics_meg_2_2024 %>% select(-Mega_bi_ps, -Mega_bi_no_ps )

# Join Osmia and Megachile data together
conspecifics_both_1_2024 <- merge(conspecifics_os_2_2024, conspecifics_meg_2_2024)


```

```{r Cleaning_Round_2_2023}
 

## Cleaning required after previous steps 

# remove rest of no_visits and non_existents (had to leave them in for the loop)
conspecifics_both_2023 <- conspecifics_both_1_2023 %>% filter(Status != 'no_visit' & Status != 'non_existent') 

# make sure no duplicates of Bee_choice for new nests 
conspecifics_choice_1_2023 <- conspecifics_both_2023 %>% filter(Bee_choice == 1)
conspecifics_choice_1_2023$Bee_choice[duplicated(conspecifics_choice_1_2023$Nest_ID)] <- NA
conspecifics_choice_0_2023 <- conspecifics_both_2023 %>%
  filter(Bee_choice == 0 | is.na(Bee_choice))
conspecifics_2023 <- rbind(conspecifics_choice_1_2023, conspecifics_choice_0_2023)

sum(conspecifics_2023$Bee_choice, na.rm = TRUE) # 228 new nests, real number


```

```{r Cleaning_Round_2_2024}
 

## Cleaning required after previous steps 

# remove rest of no_visits and non_existents (had to leave them in for the loop)
conspecifics_both_2024 <- conspecifics_both_1_2024 %>% filter(Status != 'no_visit' & Status != 'non_existent') 

# make sure no duplicates of Bee_choice for new nests 
conspecifics_choice_1_2024 <- conspecifics_both_2024 %>% filter(Bee_choice == 1)
conspecifics_choice_1_2024$Bee_choice[duplicated(conspecifics_choice_1_2024$Nest_ID)] <- NA
conspecifics_choice_0_2024 <- conspecifics_both_2024 %>%
  filter(Bee_choice == 0 | is.na(Bee_choice))
conspecifics_2024 <- rbind(conspecifics_choice_1_2024, conspecifics_choice_0_2024)

sum(conspecifics_2024$Bee_choice, na.rm = TRUE) # 81 new nests, real number


```

```{r Counting_New_Nests_2023}
 

## Counting the number of new nests


## Count number of new osmia nests per trapnest 
summ_new_os_2023 <- conspecifics_2023 %>%
  filter(Bee_choice == 1 & Occupant == 'osmia') %>%  
  group_by(Trapnest, Date) %>%
  summarize(New_nests_os = sum(Bee_choice == 1)) 
# New_nests_os: number of new osmia nests for each trapnest and date combo, currently only has values for days with at least 1 new nest

## Count number of new megachile nests per trapnest 
summ_new_meg_2023 <- conspecifics_2023 %>%
  filter(Bee_choice == 1 & Occupant ==  'megachile') %>% 
  group_by(Trapnest, Date) %>%
  summarize(New_nests_meg = sum(Bee_choice == 1))
# New_nests_meg: number of new megachile nests for each trapnest and date combo

# merge together
conspecifics_and_avail_2023 <- inner_join(conspecifics_2023, summ_avail_2023) 
new_nests_os_2023 <- full_join(conspecifics_and_avail_2023, summ_new_os_2023)
prefs_2023 <- full_join(new_nests_os_2023, summ_new_meg_2023)

# change New_nests_os to have 0s for days with no values
prefs_2023$New_nests_os <- replace(prefs_2023$New_nests_os, is.na(prefs_2023$New_nests_os), 0)
prefs_2023$New_nests_meg <- replace(prefs_2023$New_nests_meg, is.na(prefs_2023$New_nests_meg), 0)


```

```{r Counting_New_Nests_2024}
 

## Counting the number of new nests


## Count number of new osmia nests per trapnest 
summ_new_os_2024 <- conspecifics_2024 %>%
  filter(Bee_choice == 1 & Occupant == 'osmia') %>%  
  group_by(Trapnest, Date) %>%
  summarize(New_nests_os = sum(Bee_choice == 1)) 
# New_nests_os: number of new osmia nests for each trapnest and date combo, currently only has values for days with at least 1 new nest


## Count number of new megachile nests per trapnest 
summ_new_meg_2024 <- conspecifics_2024 %>%
  filter(Bee_choice == 1 & Occupant ==  'megachile') %>% 
  group_by(Trapnest, Date) %>%
  summarize(New_nests_meg = sum(Bee_choice == 1))
# New_nests_meg: number of new megachile nests for each trapnest and date combo

# merge together
conspecifics_and_avail_2024 <- inner_join(conspecifics_2024, summ_avail_2024) 
new_nests_os_2024 <- full_join(conspecifics_and_avail_2024, summ_new_os_2024)
prefs_2024 <- full_join(new_nests_os_2024, summ_new_meg_2024)

# change New_nests_os to have 0s for days with no values
prefs_2024$New_nests_os <- replace(prefs_2024$New_nests_os, is.na(prefs_2024$New_nests_os), 0)
prefs_2024$New_nests_meg <- replace(prefs_2024$New_nests_meg, is.na(prefs_2024$New_nests_meg), 0)


```

```{r Weather_2023}
 

## Creating column with number of good days for bee activity based on weather between my visits to the trapnests 

weather_2023 <- read_csv('Data/Weather_2023_data.csv') 

# remove empty rows
weather_2023 <- weather_2023[rowSums(is.na(weather_2023)) != ncol(weather_2023), ]
# remove empty columns
weather_2023 <- Filter(function(x)!all(is.na(x)), weather_2023)

# replaces /NA/ with NA fr visit columns
weather_2023 <- weather_2023 %>% mutate(Visit_NN = if_else(is.na(Visit_NN), 'NA', Visit_NN))
weather_2023 <- weather_2023 %>% mutate(Visit_CP = if_else(is.na(Visit_CP), 'NA', Visit_CP))
weather_2023 <- weather_2023 %>% mutate(Visit_BP_Os = if_else(is.na(Visit_BP_Os), 'NA', Visit_BP_Os))
weather_2023 <- weather_2023 %>% mutate(Visit_BP_Meg = if_else(is.na(Visit_BP_Meg), 'NA', Visit_BP_Meg))

# replace /NA/ with zeros in weather count columns
weather_2023 <- weather_2023 %>% mutate(Good_days_NN = if_else(is.na(Good_days_NN), 0, Good_days_NN))
weather_2023 <- weather_2023 %>% mutate(Good_days_CP = if_else(is.na(Good_days_CP), 0, Good_days_CP))
weather_2023 <- weather_2023 %>% mutate(Good_days_BP_Os = if_else(is.na(Good_days_BP_Os), 0, Good_days_BP_Os))
weather_2023 <- weather_2023 %>% mutate(Good_days_BP_Meg = if_else(is.na(Good_days_BP_Meg), 0, Good_days_BP_Meg))

table(weather_2023$Weather) # 31 bad days, 65 good days for bee activity  
str(weather_2023)

## Bind together

# take only columns I need, for each site
w_NN_2023 <- weather_2023 %>% select(Date, Good_days_NN)
w_BP_Os_2023 <- weather_2023 %>% select(Date, Good_days_BP_Os)
w_BP_Meg_2023 <- weather_2023 %>% select(Date, Good_days_BP_Meg)
w_CP_2023 <- weather_2023 %>% select(Date, Good_days_CP)

# divide data frames into their sites to properly link up the weather data
NN_2023 <- prefs_2023 %>% filter(Site == 'NN')
BP_Os_2023 <- prefs_2023 %>% filter(Subsite == 'A' | Subsite == 'B' | Subsite == 'C' | Subsite == 'D' | Subsite == 'E' | Subsite == 'F')
BP_Meg_2023 <- prefs_2023 %>% filter(Subsite == 'M' | Subsite == 'N' | Subsite == 'O' | Subsite == 'P' | Subsite == 'Q' | Subsite == 'R')
CP_2023 <- prefs_2023 %>% filter(Site == 'CP')

# Join weather data 
pref_NN_2023 <- left_join(NN_2023, w_NN_2023)
pref_BP_Os_2023 <- left_join(BP_Os_2023, w_BP_Os_2023)
pref_BP_Meg_2023 <- left_join(BP_Meg_2023, w_BP_Meg_2023)
pref_CP_2023 <- left_join(CP_2023, w_CP_2023)
# rename good days column
pref_NN_2023 <- rename(pref_NN_2023, Good_days = Good_days_NN)
pref_BP_Os_2023 <- rename(pref_BP_Os_2023, Good_days = Good_days_BP_Os)
pref_BP_Meg_2023 <- rename(pref_BP_Meg_2023, Good_days = Good_days_BP_Meg)
pref_CP_2023 <- rename(pref_CP_2023, Good_days = Good_days_CP)

# bind together
preferences_2023 <- rbind(pref_BP_Os_2023, pref_NN_2023)
preferences_2023 <- rbind(preferences_2023, pref_BP_Meg_2023)
preferences_2023 <- rbind(preferences_2023, pref_CP_2023)

# compare new df to the old intact one, should be the same
length(prefs_2023$Trapnest) # 26568
length(preferences_2023$Trapnest) # 26568


```

```{r Weather_2024}
 

## Creating column with number of good days for bee activity based on weather between my visits to the trapnests 

weather_2024 <- read_csv('Data/Weather_2024_data.csv') 

# remove empty columns
weather_2024 <- Filter(function(x)!all(is.na(x)), weather_2024)

table(weather_2024$Weather) # 23 bad days, 49 good days for bee activity  
str(weather_2024)

# replace /NA/ with zeros in weather count columns
weather_2024 <- weather_2024 %>% mutate(Good_days_CP = if_else(is.na(Good_days_CP), 0, Good_days_CP))
weather_2024 <- weather_2024 %>% mutate(Good_days_BP = if_else(is.na(Good_days_BP), 0, Good_days_BP))

## Bind together

# take only columns I need, for each site
w_BP_2024 <- weather_2024 %>% select(Date, Good_days_BP)
w_CP_2024 <- weather_2024 %>% select(Date, Good_days_CP)

# divide data frames into their sites to properly link up the weather data

BP_2024 <- prefs_2024 %>% filter(Site == 'BP')
CP_2024 <- prefs_2024 %>% filter(Site == 'CP')

# Join weather data 
pref_BP_2024 <- left_join(BP_2024, w_BP_2024)
pref_CP_2024 <- left_join(CP_2024, w_CP_2024)

# rename good days column
pref_BP_2024 <- rename(pref_BP_2024, Good_days = Good_days_BP)
pref_CP_2024 <- rename(pref_CP_2024, Good_days = Good_days_CP)

# bind together
preferences_2024 <- rbind(pref_BP_2024, pref_CP_2024)

# compare new df to the old intact one, should be the same
length(prefs_2024$Trapnest) # 13284
length(preferences_2024$Trapnest) # 13284


```

```{r Merging_Preferences_data}
 
# merge together 2023 and 2024 bee choice data
preferences_1 <- rbind(preferences_2023, preferences_2024)

# Inspect
# do the lengths add up?
length(preferences_2023$Date)
length(preferences_2024$Date)
# 26568 + 13284 = 39852 - matches preferences 
table(preferences_1$Occupant)

```

```{r Calculating_Prior_Values}
 

## Changing occupant count for prior number to be the average number of congenera 

# When I'm looking at bee preferences, I need the values prior to the bee deciding to build her nest. E.g., how many nests existed when the bee decided to establish her nest.
# When I'm looking at parasite density, I need the total values, not the prior values. E.g., how many existing nests are there in a trapnest when a parasite decides to lay an egg

# need to make theses columns the number of occupencies PRIOR to the bee nesting, e.g., the new nests should not count in Osmia_ps and Osmia_no_ps
# If theres 1 new nest, make new column to say Osmia_(no_)ps - New_nests_os
# If there are multiple nests, to take the average, do ((n-1)/2) + (Osmia_ps - New_nests_os), n being the number of new nests per genera. Osmia_ps if the total count of osmia in the trapnest, not the prior count
# e.g., 1 new nest, 9 Osmia_ps = 9-1 = 8
# e.g, 3 new nests, 9 Osmia_ps (so only 6 were filled the previous visit) = ((3-1)/2) + (9-3) = 7
# Osmia_ps_prior + Available_prior should usually = 18, unless there's non-target occupants

# 1- for 0 or 1 new nests, (available_post - new nests) 
  # osmia pseudo 
preferences_1 <- preferences_1 %>% mutate(Osmia_ps_prior_V1 = ifelse(New_nests_os == 1 | New_nests_os == 0, (Osmia_ps - New_nests_os), 'TBD'))
  # osmia no pseudo
preferences_1 <- preferences_1 %>% mutate(Osmia_no_ps_prior_V1 = ifelse(New_nests_os == 1 | New_nests_os == 0, (Osmia_no_ps - New_nests_os), 'TBD'))
  # megachile pseudo
preferences_1 <- preferences_1 %>% mutate(Meg_ps_prior_V1 = ifelse(New_nests_meg == 1 | New_nests_meg == 0, (Meg_ps - New_nests_meg), 'TBD'))
  # megachile no pseudo
preferences_1 <- preferences_1 %>% mutate(Meg_no_ps_prior_V1 = ifelse(New_nests_meg == 1 | New_nests_meg == 0, (Meg_no_ps - New_nests_meg), 'TBD'))

# 2 A- for multiple new nests, (n-1)/2
  # osmia
preferences_1 <- preferences_1 %>% mutate(Osmia_equ = if_else(New_nests_os > 1, ((New_nests_os - 1)/2), NA))
  # megachile
preferences_1 <- preferences_1 %>% mutate(Meg_equ = if_else(New_nests_meg > 1, ((New_nests_meg - 1)/2), NA))

# B- add equation + (available_post - new nests)
  # osmia pseudo
preferences_1 <- preferences_1 %>% mutate(Osmia_ps_prior = ifelse(Osmia_ps_prior_V1 == 'TBD', (Osmia_equ + Osmia_ps - New_nests_os), ifelse(is.na(Osmia_equ) & !is.na(Osmia_ps_prior_V1) | Osmia_ps_prior_V1 != 'TBD', Osmia_ps_prior_V1, 'leftover' )))
  # osmia no pseudo
preferences_1 <- preferences_1 %>% mutate(Osmia_no_ps_prior = ifelse(Osmia_no_ps_prior_V1 == 'TBD', (Osmia_equ + Osmia_no_ps - New_nests_os), ifelse(is.na(Osmia_equ) & !is.na(Osmia_no_ps_prior_V1) | Osmia_no_ps_prior_V1 != 'TBD', Osmia_no_ps_prior_V1, 'leftover' )))
  # megachile pseudo
preferences_1 <- preferences_1 %>% mutate(Meg_ps_prior = ifelse(Meg_ps_prior_V1 == 'TBD', (Meg_equ + Meg_ps - New_nests_meg), ifelse(is.na(Meg_equ) & !is.na(Meg_ps_prior_V1) | Meg_ps_prior_V1 != 'TBD', Meg_ps_prior_V1, 'leftover' ))) 
  # megachile no pseudo
preferences_1 <- preferences_1 %>% mutate(Meg_no_ps_prior = ifelse(Meg_no_ps_prior_V1 == 'TBD', (Meg_equ + Meg_no_ps - New_nests_meg), ifelse(is.na(Meg_equ) & !is.na(Meg_no_ps_prior_V1) | Meg_no_ps_prior_V1 != 'TBD', Meg_no_ps_prior_V1, 'leftover' )))

# take only columns I need
preferences <- preferences_1 %>% select(Date, Site, Subsite, Treatment, Trapnest, Cavity_number, Straw_ID, Cavity_size, Filled_length_mm, Straw_length_mm, Nest_ID, Cavity_ID, Status, Contains_cells, Occupant, Good_days, Bee_choice, Available_post, New_nests_os, New_nests_meg, Osmia_ps, Osmia_no_ps, Meg_ps, Meg_no_ps, Osmia_ps_prior, Osmia_no_ps_prior, Meg_ps_prior, Meg_no_ps_prior)

# since I'm looking at new nests, I'm not going to make the other colums like osmia_ps_prior etc 'NA' is Bee-choice is NA, because there shouldnt be a time where I'm using those values if Bee_choice isn't 1 or 0

```

```{r Available_Cavities_Prior}

## Making column for the number of available cavities that could have been occupied
 
# Available_cavities_prior = Available_post - New_nests_sum

# Sum the megachile and osmia nests on the same day
# if one column is NA and the other isn't, put the column that isn't NA, but if there's values in both, add them together
preferences <- preferences %>% mutate(New_nests_sum = if_else(!is.na(New_nests_os) & is.na(New_nests_meg), New_nests_os, if_else(is.na(New_nests_os) & !is.na(New_nests_meg), New_nests_meg, (New_nests_os + New_nests_meg))))

preferences <- preferences %>% mutate(Available_cavities_prior = Available_post + New_nests_sum)

# filter out wasps and non-targets from choices, after we counted them as occupied cavities, but do this in the next chunk


```

```{r Emergence_Wrangling}


# nesting_cells is the nesting data with cell-level observations

# Columns 
 # Cumulative_par: cumulative number of parasites for that specific nest. E.g., 6_15a had no parasites when 1 cell was built, then two more cells each had a parasite, then six more cells with three parasites. So cumulative_par is 0, 2, then 5, and 5 until the nest is removed 
 # Number_of_cells: the cumulative number of cells in the nest at the time. Comes from parasite data
 # Cell_parasitized: if that cell is parasitized, binary
# NOTE: some columns have duplicated data after merging, eg., multiple 1s for Bee_choice or duplicated straw length and filled length


## Question 3: Do parasites affect nesting preferences ##

# load data
emergence_2023 <- read_csv('Data/Emergence_data_2023.csv')  
emergence_2024 <- read_csv('Data/Emergence_data_2024.csv')  

# inspect
table(emergence_2023$Cell_occupant)
table(emergence_2024$Cell_occupant)


## Merge dfs and wrangle cell_number and cell_position, and create cell_parasitized  

# make column to turn cell number into cell position for emergence_2023
# take max number of each nest
emergence_2023 <- emergence_2023 %>%
  arrange(Nest_ID, Date) %>%
  group_by(Nest_ID) %>%
  mutate(Cell_position_2 = if_else(Cell_number == max(Cell_number), 'last cell', 'not last cell')) %>%
  ungroup()

# merge together the two Cell_position columns and rename for 2023 data
emergence_2023 <- emergence_2023 %>%
  mutate(Cell_position_combined = coalesce(Cell_position, Cell_position_2))
emergence_2023 <- emergence_2023 %>% select(-Cell_position, -Cell_position_2)
emergence_2023 <- emergence_2023 %>% rename(Cell_position = Cell_position_combined)

# NOTE: the cell_number column does not always indicate the order of cells built for the 2024 data, especially if there are multiple built on the same day. It's a way to distinguish the cell-level data. What's imrpotant is the date each cell was built, and weather its the last cell or not (Cell_position)


## Make a cell number column for 2024 data, and fill in the blanks for the 2023 data

# add in the ascending number
emergence_2024 <- emergence_2024 %>%
  arrange(Nest_ID, Date) %>% 
  group_by(Nest_ID) %>% 
  mutate(Cell_number = row_number())

emergence_2023 <- emergence_2023 %>%
  arrange(Nest_ID, Date) %>% 
  group_by(Nest_ID) %>%
  mutate(
    Cell_number = if_else(
      is.na(Cell_number), 
      row_number(),
      Cell_number)) %>%
  ungroup()

# bind dfs together
emergence <- bind_rows(emergence_2023, emergence_2024)
length(emergence_2023$Site) + length(emergence_2024$Site) # = length(emergence$Site) 

# make cell ID column
emergence$Cell_ID <- with(emergence, paste(Nest_ID, Cell_number, sep = '_'))

# rearrange and remove columns I don't need
emergence <- emergence %>% select(Site, Subsite, Trapnest, Treatment, Cavity_size, Cavity_number, Straw_ID, Nest_ID, Cell_number, Cell_ID, Cell_position, Date, Cell_occupant,  Species_or_subtype)


## Filter out non-target occupants

  # first, straight from the emergence data
non_target <- c('heriades', 'hoplitis', 'hyleaus', 'masked bee', 'non-target bee', 'NA', 'resin bee', 'wasp')
emergence <- emergence %>%
  group_by(Nest_ID) %>%
  filter(!any(Cell_occupant %in% non_target)) %>%  
  ungroup()
table(emergence$Cell_occupant)


  # second, remove from the emergence data again, but using the occupant column in preferences (to catch nests that didn't develope enough to emerge, but we know based on their nesting material from the field data)
table(preferences$Occupant)
nests_to_remove <- preferences %>% 
  filter(Occupant %in% non_target) %>% 
  pull(Nest_ID) %>%
  unique()
emergence <- emergence %>%
  filter(!Nest_ID %in% nests_to_remove)

  # finally, filter out the non-target occupants in the preferences data
preferences <- preferences %>% filter(Occupant == 'osmia' | Occupant =='megachile' | Occupant == 'none')


## Wrangle number of cells and parasites

# create column to say if cell is parasitized or not, or NA for unknowns
table(emergence$Cell_occupant)
emergence <- emergence %>%
  mutate(Cell_parasitized = if_else(Cell_occupant == 'parasite', 1,
                                    if_else(Cell_occupant == 'osmia' | Cell_occupant == 'megachile', 0, NA)))

# take number of cells total for that nest and date combo
emergence <- emergence %>% 
    group_by(Nest_ID, Date) %>% 
    mutate(Number_of_cells = max(Cell_number))

# check that each nest has only one type of bee, e.g., not mislabelled 
emergence %>%
  group_by(Nest_ID) %>%
  summarise(Occupants = paste(unique(Cell_occupant), collapse = ', '),
      .groups = 'drop')


## Make column to say nest is parasitized or not for when a parasite is in a cell, from that date onwards

# make column to say for each date, if a cell has parasites, then count cumulative parasites in a new column, and keep the value even when the cells between bees and parasites are NAs (e.g., mold or empty)

emergence <- emergence %>%
  arrange(Nest_ID, Date) %>%
  group_by(Nest_ID) %>%
  mutate(Tempor_cum = cumsum(replace_na(Cell_parasitized, 0)), # temporarily replace NA with 0
          seen_any = cumsum(!is.na(Cell_parasitized)),
          Cumulative_par = if_else(seen_any == 0, NA_real_, Tempor_cum)) %>%
  select(-Tempor_cum, -seen_any)

# take max number of parasites for a nest_ID - date combo
# e.g., on 2023-06-14 for 13_18a (cells 1 and 2), both are parasitized, so take the highest parasite count for that date, so say for 13_18a on 2023-06-14, there's 2 parasites
emergence <- emergence %>% 
  group_by(Date, Nest_ID) %>% 
  mutate(Cumulative_par_max = max(Cumulative_par)) %>% 
  ungroup() 


## Bind emergence and preferences data 

# preferences has one row per nest and date, while emergence data has multiple rows per date (one per cell)
emergence$Trapnest <- paste('trapnest', emergence$Trapnest, sep = '_')
emerg_and_pref <- full_join(emergence, preferences) 


## Inspect

 # check for Date mismatches

setdiff(emergence$Date, preferences$Date) # no Dates are in emergence but not in preferences
setdiff(preferences$Date, emergence$Date) # some dates are in preferences but not emergence because we visited the field but don't have emergence data for that day (e.g., only non-target activity or no field activity)


 # check for Nest_ID mismatches

setdiff(emergence$Nest_ID, preferences$Nest_ID)  # IDs in emergence but not in preferences: 
  # 18_8b: must be mislabelled, remove. 64_14b, 73_10b and 75_5b are non-target bees that never developped
emerg_and_pref <- emerg_and_pref %>% filter(Nest_ID != '18_8b' & Nest_ID != '64_14b' & Nest_ID != '73_10b' & Nest_ID != '75_5b')

# see below for IDs in preferences but not in emergence
# compare the nest IDs in the dfs of nests with activity

# nest_IDs_preferences <- preferences %>%
#   filter(Status != 'pseudo' & Status != 'empty' & Status != 'no change' & Bee_choice == 1 & Contains_cells == 1) %>%
#   group_by(Nest_ID) %>%
#   ungroup() %>%
#   arrange(Nest_ID)
# nest_IDs_preferences <- nest_IDs_preferences %>% select(Nest_ID)
# 
# nest_IDs_emergence <- emergence %>%
#   group_by(Nest_ID) %>%
#   slice(1) %>%
#   ungroup() %>%
#   arrange(Nest_ID)
# nest_IDs_emergence <- nest_IDs_emergence %>% select(Nest_ID)
# 
# anti_join_1 <- anti_join(nest_IDs_preferences, nest_IDs_emergence) # IDs in preferences not in emergence
# anti_join_2 <- anti_join(nest_IDs_emergence, nest_IDs_preferences) # IDs in emergence not in preferences

# IDs in preferences but not in emergence:
# listing the reasons for discrepencies: 
# cell not completed (abandoned or just end cap and inner wall), thus nothing to emerge: 
  # anti_join_1: 43_11a, 43_14a, 44_5a, 5_12a, 50_10a, 76_11a, 83_9b, 84_13b, 93_15b
  # anti_join_2: 16_11a, 17_7a, 7_3c, 78_17a, 84_7b
# nests eaten in the field by birds or insects, thus nothing to emerge: 
  # 23_15a, 24_15a, 26_10a, 31_3a, 32_7a, 5_9a, 59_16a, 7_16a, 7_17b, 81_12b, 81_16b, 81_5a
# nests without emergence data. Unclear why, perhaps not recorded or their nest was too moldy: 
  # anti_join_1: 1_16a, 17_1b, 24_9a, 25_11a, 3_13b, 30_11b, 42_2b, 43_11b, 43_4a, 49_4b, 59_4b, 6_9b, 67_16a, 71_14a, 71_2a, 71_4a
  # anti_join_2: 15_4a, 16_1a, 17_18a, 17_9a, 2_18a, 25_16b, 25_1a, 25_4a, 30_7a, 35_8a, 36_3b, 59_4a, 6_17a, 7_4a, 8_12a, 9_9b
# nests that are mislabelled (exist in emergence data but not preferences): 13_15a, 43_3a, 6_10a, 18_8b

# remove the mislabelled nests
emerg_and_pref <- emerg_and_pref %>% filter(Nest_ID != '13_15a' & Nest_ID != '43_3a' & Nest_ID != '6_10a' & Nest_ID != '25_16b')


# bee_choice now has some duplicates after merging into emerg_and_pref, so make the duplicates NA
emerg_and_pref <- emerg_and_pref %>%
  group_by(Nest_ID) %>% 
  arrange(Nest_ID, Date) %>%
  mutate(Bee_choice = if_else(row_number() == min(which(Bee_choice == 1)), 1, NA)) %>%
  ungroup() # ignore warnings about using min() on NAs

# numbers of new nests 
sum(preferences$Bee_choice, na.rm = TRUE)  # 307, which includes the nests with only inner walls

table(preferences %>% 
        filter(Bee_choice == 1) %>% 
        pull(Contains_cells)) # 261, this includes only Megachile and Osmia nests that have at least 1 cell, and 46 that don't include cells
# check that there are no duplicates of contains_cells to make sure there are truly 261 new nests
preferences %>%
  filter(Bee_choice == 1) %>%
  group_by(Nest_ID) %>%
  filter(n_distinct(Contains_cells) > 1) %>%
  ungroup() # 0
# number of nests from emergence data
length(unique(emergence$Nest_ID)) # 247 

# are any of the Statuses NA? Should be none, remove because they are from non-target bees
emerg_and_pref_v2 <- emerg_and_pref %>% filter(!is.na(Status))
sum(is.na(emerg_and_pref_v2$Status)) # 0


## Making values consistent for throughout the time the nest is in the trapnest

# emerg_and_pref should have the values for number_of_cells and cumulative_par(_max) for only the dates with activity. The loop will make those values consistent throughout the time the nest is in the trapnest


# ## Loop 1 for making the cumulative_par_max value for the duration the nest is in the trapnest 
#
# # make sure data is arranged chronologically
# emerg_and_pref <- emerg_and_pref %>% arrange(Nest_ID, Date)
# # initiate new column, then fill it in
# emerg_and_pref$Cumulative_par_V2 <- emerg_and_pref$Cumulative_par_max 
# 
# # loop takes too long to do at once, so remove all empty and pseudo, then adding back in after. Tested this code at the bottom chucnk called Example Code
# emerg_and_pref_excluded <- emerg_and_pref %>% filter(Status != 'empty' & Status != 'pseudo') # excluding empty and pseudo
# 
# ### START
# for(i in 1:nrow(emerg_and_pref_excluded)){
#   nestID <- emerg_and_pref_excluded$Nest_ID[i] # focal nest for i-th row
#   dt <- emerg_and_pref_excluded$Date[i] # date for i-th row
#   allprev <- emerg_and_pref_excluded %>% filter(Nest_ID == nestID & Date <= dt) %>% pull(Cumulative_par_max) # all previous parasite counts for that focal nest
#   
#   check1 <- !all(is.na(allprev))
#   check2 <- !emerg_and_pref_excluded$Status[i] %in% c('empty', 'pseudo') 
# 
#   if(check1 & check2){
#     emerg_and_pref_excluded$Cumulative_par_V2[i] <- max(allprev, na.rm = T)
#   }
# } ### END
# 
# 
# # bind back together
# emerg_and_pref_include <- emerg_and_pref %>% filter(Status == 'empty' | Status == 'pseudo') # include empty and pseudo 
# emerg_and_pref_v2 <- rbind(emerg_and_pref_excluded, emerg_and_pref_include) # 39,756
# emerg_and_pref_v2 <- emerg_and_pref_v2 %>% arrange(Nest_ID, Date)
# # remove unnecessary columns
# emerg_and_pref_v2 <- ungroup(emerg_and_pref_v2)
# emerg_and_pref_v2 <- emerg_and_pref_v2 %>% select(-Cumulative_par, -Cumulative_par_max)
# # rename column and df
# emerg_and_pref_v2 <- emerg_and_pref_v2 %>% rename(Cumulative_par = Cumulative_par_V2)
# 
# # inspect
# inspect_parasite_loop_1 <- emerg_and_pref_v2 %>% filter(Status != 'empty' & Status != 'pseudo')


# ## Loop 2 for making the Number_of_cells value for the duration the nest is in the trapnest 
# 
# # arrange data chronologically
# emerg_and_pref_v2 <- emerg_and_pref_v2 %>% arrange(Nest_ID, Date)
# # initiate new column, then fill it in
# emerg_and_pref_v2$Number_of_cells_V2 <- emerg_and_pref_v2$Number_of_cells 
# 
# # loop takes too long to do at once, so remove all empty and pseudo, then adding back in after.
# emerg_and_pref_v2_excluded <- emerg_and_pref_v2 %>% filter(Status != 'empty' & Status != 'pseudo') # excluding empty and pseudo
# 
# ### START
# for(i in 1:nrow(emerg_and_pref_v2_excluded)){
#   nestID <- emerg_and_pref_v2_excluded$Nest_ID[i] # focal nest for i-th row
#   dt <- emerg_and_pref_v2_excluded$Date[i] # date for i-th row
#   allprev <- emerg_and_pref_v2_excluded %>% filter(Nest_ID == nestID & Date <= dt) %>% pull(Number_of_cells_V2) # all previous parasite counts for that focal nest
#   
#   check1 <- !all(is.na(allprev))
#   check2 <- !emerg_and_pref_v2_excluded$Status[i] %in% c('empty', 'pseudo') 
# 
#   if(check1 & check2){
#     emerg_and_pref_v2_excluded$Number_of_cells_V2[i] <- max(allprev, na.rm = T)
#   }
# } ### END
# 
# # bind back together
# emerg_and_pref_v2_include <- emerg_and_pref_v2 %>% filter(Status == 'empty' | Status == 'pseudo') # include empty and pseudo
# emerg_and_pref_v3 <- rbind(emerg_and_pref_v2_excluded, emerg_and_pref_v2_include)
# emerg_and_pref_v3 <- emerg_and_pref_v3 %>% arrange(Nest_ID, Date)
# # remove unnecessary columns
# emerg_and_pref_v3 <- ungroup(emerg_and_pref_v3)
# emerg_and_pref_v3 <- emerg_and_pref_v3 %>% select(-Number_of_cells)
# # rename column and df
# emerg_and_pref_v3 <- emerg_and_pref_v3 %>%
#   rename(Number_of_cells = Number_of_cells_V2)
# 
# # rearrange columns 
# emerg_and_pref_v3 <- emerg_and_pref_v3 %>% select(Site, Subsite, Trapnest, Treatment, Cavity_size, Cavity_number, Straw_ID, Nest_ID, Cell_number, Cell_ID, Cell_position, Date, Cell_occupant, Species_or_subtype, Cell_parasitized, Cumulative_par, Number_of_cells, Filled_length_mm, Straw_length_mm, Cavity_ID, Status, Contains_cells, Occupant, Good_days, Bee_choice, Available_post, New_nests_os, New_nests_meg, Osmia_ps, Osmia_no_ps, Meg_ps, Meg_no_ps, Osmia_ps_prior, Osmia_no_ps_prior, Meg_ps_prior, Meg_no_ps_prior, Osmia_ps_no_iw, Osmia_no_ps_no_iw, Meg_ps_no_iw, Meg_no_ps_no_iw, New_nests_sum, Available_cavities_prior)
# 
# # inspect
# inspect_parasite_loop_2 <- emerg_and_pref_v3 %>% filter(Status != 'empty' & Status != 'pseudo' & is.na(Number_of_cells))
# # most NAs are from inner walls then no change


## Number of cells parasitized per number of cells in the nest 

# emerg_and_pref_v3$Number_of_cells <- as.numeric(emerg_and_pref_v3$Number_of_cells)
emerg_and_pref_v2$Osmia_ps_prior <- as.numeric(emerg_and_pref_v2$Osmia_ps_prior)
emerg_and_pref_v2$Osmia_no_ps_prior <- as.numeric(emerg_and_pref_v2$Osmia_no_ps_prior)
emerg_and_pref_v2$Meg_ps_prior <- as.numeric(emerg_and_pref_v2$Meg_ps_prior)
emerg_and_pref_v2$Meg_no_ps_prior <- as.numeric(emerg_and_pref_v2$Meg_no_ps_prior)

nesting_0 <- emerg_and_pref_v2 # %>% mutate(Prop_cells_par = (Cumulative_par/Number_of_cells)) 


# first I am keeping all cells for the nest in the df, then will divide the df into cell-level observations, and nest-level observations. There are some columns that are currently repeated and thus incorrect, but will later be corrected. For ex, Bee_choice for once nest can have multiples 1s is multiple cells were built on the same day. Later I remove duplicates so that the nest-level counts are accurate again.


## Making the active period
# Wasn't working in a loop or even a single if_else statement, so broke it up

  # Step 1: if_else #
# criteria: within Nest_ID, starts with Bee_choice being 1, ends with anything containing 'end cap'

# make column to say if it contains 'end cap' or not
nesting_0$End_cap <- grepl('end cap', nesting_0$Status)
# make column to say if it's sealed (by containing an end cap)
nesting_0 <- nesting_0 %>% mutate(Sealed = if_else(is.na(Bee_choice) & End_cap == TRUE | Bee_choice == 1 & End_cap == TRUE, 'sealed',
                                                if_else(Bee_choice == 0 | is.na(Bee_choice) & Status == 'pseudo', 'NA_',
                                                       if_else(Bee_choice == 1 & End_cap == FALSE, 'not sealed', 'leftover'))))

# inspecting to see if it worked
# insp_sealed <- nesting_0 %>% filter(Sealed == 'sealed') # yes
# insp_not_sealed <- nesting_0 %>% filter(Sealed == 'not sealed') # great
# insp_end_cap_T <- nesting_0 %>% filter(End_cap == TRUE) # wonderful
# insp_end_cap_F <- nesting_0 %>% filter(End_cap == FALSE) # amazing

  # Step 2: Loop 3 #

# arrange data chronologically
nesting_0 <- nesting_0 %>% arrange(Nest_ID, Date)
# use 7_3b for ex, is not sealed, NA, sealed, NA, want to make 7_3b not sealed, not sealed, sealed, sealed.
# use 7_8a for ex to see if multiple rows (three NAs) all say not sealed
# initiate new column, then fill it in
nesting_0$Sealed_V2 <- nesting_0$Sealed 

# loop takes too long to do at once, so remove all empty and pseudo, then adding back in after.
nesting_0_exclude <- nesting_0 %>% filter(Status != 'empty' & Status != 'pseudo') # excluding empty and pseudo

### START
for(i in 1:nrow(nesting_0_exclude)){
  nestID <- nesting_0_exclude$Nest_ID[i] # focal nest for i-th row
  dt <- nesting_0_exclude$Date[i] # date for i-th row
  allprev <- nesting_0_exclude %>% filter(Nest_ID == nestID & Date <= dt) %>% pull(Sealed_V2) # all sealed statuses for that focal nest
  
  check1 <- !all(is.na(allprev))

  if(check1){
    nesting_0_exclude$Sealed_V2[i] <- max(allprev, na.rm = T)
  }
} ### END


# bind back together
nesting_0_include <- nesting_0 %>% filter(Status == 'empty' | Status == 'pseudo') # include empty and pseudo 
nesting_0 <- rbind(nesting_0_exclude, nesting_0_include) 
nesting_0 <- nesting_0 %>% arrange(Nest_ID, Date)

# inspect
inspect_parasite_loop_3 <- nesting_0 %>% filter(Status != 'empty' & Status != 'pseudo') 

# several rows to manually fix: nest IDs 5_9a, 5_18a, 7_16a, 7_17b, 23_15a, 24_15a, 24_18a, 26_10a, 31_3a, 32_9a, 32_7a, 59_16a, 81_12b, 81_16b, 81_5a were all eaten at some point by birds or insects, so they appear as sealed or not sealed, then should again appear as NA (because they become empty), I will manually override these
# find these by sorting by Status then Sealed

# if the Nest_ID == any of those eaten nests above, then say NA_, otherwise say Sealed_V2
nesting_0 <- nesting_0 %>%
  mutate(
    Sealed_V3 = if_else(
      Status == 'empty' & Nest_ID %in% c('5_9a', '5_18a', '7_16a', '7_17b', '23_15a', '24_15a', '24_18a', '26_10a', '31_3a', '32_9a', '32_7a', '59_16a', '81_12b', '81_16b', '81_5a'),
      'NA_',
      Sealed_V2
    )
  )

# clean up df
nesting_cells_0 <- nesting_0 %>% select(Site, Subsite, Trapnest, Treatment, Cavity_size, Cavity_number, Straw_ID, Nest_ID, Cell_number, Cell_ID, Cell_position, Date, Cell_occupant, Species_or_subtype, Cell_parasitized, Cumulative_par, Number_of_cells, Filled_length_mm, Straw_length_mm, Cavity_ID, Status, Contains_cells, Occupant, Good_days, Bee_choice, Available_post, New_nests_os, New_nests_meg, Osmia_ps, Osmia_no_ps, Meg_ps, Meg_no_ps, Osmia_ps_prior, Osmia_no_ps_prior, Meg_ps_prior, Meg_no_ps_prior, New_nests_sum, Available_cavities_prior, Sealed_V3)
# rename and fix NAs
nesting_cells_0 <- rename(nesting_cells_0, Sealed = Sealed_V3)
nesting_cells_0$Sealed <- replace(nesting_cells_0$Sealed, nesting_cells_0$Sealed == 'NA_', NA)

# nesting_cells_0 is the nesting data with cell-level observations


## Make column to say nest is parasitized or not, binary, not including unknown cell occupants

nesting_cells_0 <- nesting_cells_0 %>% mutate(Nest_parasitized = if_else(is.na(Cumulative_par), NA, 
                                                   if_else(Cumulative_par == 0, 'not parasitized',
                                                          if_else(Cumulative_par >= 1, 'parasitized', 'leftover'))))

# some have NAs
# if its an inner wall only, say not parasitized 
nesting_cells_0 <- nesting_cells_0 %>%
  group_by(Nest_ID) %>%   
  mutate(
    After_inner_wall = cumsum(Status == 'inner wall'),
    Before_cells = cumsum(grepl('cell', Status, ignore.case = TRUE)),

    Nest_parasitized_v2 = case_when(
      is.na(Nest_parasitized) & Status == 'inner wall' ~ 'not parasitized',
      Status == 'no change' & After_inner_wall > 0 & Before_cells == 0 ~ 'not parasitized',
      TRUE ~ NA_character_
    )
  ) %>%
  ungroup()

# some still have NAs for Nest_parasitized
# nesting_cells_0_NA_par <- nesting_cells_0 %>% filter(!is.na(Occupant) & Occupant != 'none' & Status != 'pseudo' & is.na(Nest_parasitized) & is.na(Nest_parasitized_v2))
# all the ones that are missing for some reason (eaten, only 1 cell, no emergence data)

# combine and rename Nest_parasitized columns
nesting_cells_0 <- nesting_cells_0 %>% mutate(Nest_parasitized_v3 = coalesce(Nest_parasitized, Nest_parasitized_v2))
nesting_cells_0 <- nesting_cells_0 %>% select(-Nest_parasitized, -Nest_parasitized_v2)
nesting_cells_0 <- nesting_cells_0 %>% rename(Nest_parasitized = Nest_parasitized_v3)



## Loop 4: Make the parasitized or not parasitized carry over for the duration that the nest exists

# arrange data chronologically
nesting_cells_0 <- nesting_cells_0 %>% arrange(Nest_ID, Date)
# for ex: 102_13 has NAs between dates where it says not parasitized. should totally be not parasizted

# initiate new column, then fill it in
nesting_cells_0$Nest_parasitized_V2 <- nesting_cells_0$Nest_parasitized 

# loop takes too long to do at once, so remove all empty and pseudo, then adding back in after.
nesting_cells_0_exclude <- nesting_cells_0 %>% filter(Status != 'empty' & Status != 'pseudo') # excluding empty and pseudo

### START
for(i in 1:nrow(nesting_cells_0_exclude)){
  nestID <- nesting_cells_0_exclude$Nest_ID[i] # focal nest for i-th row
  dt <- nesting_cells_0_exclude$Date[i] # date for i-th row
  allprev <- nesting_cells_0_exclude %>% filter(Nest_ID == nestID & Date <= dt) %>% pull(Nest_parasitized_V2) # all sealed statuses for that focal nest
  
  check1 <- !all(is.na(allprev))

  if(check1){
    nesting_cells_0_exclude$Nest_parasitized_V2[i] <- max(allprev, na.rm = T)
  }
} ### END


# bind back together
nesting_cells_0_include <- nesting_cells_0 %>% filter(Status == 'empty' | Status == 'pseudo') # include empty and pseudo 
nesting_cells <- rbind(nesting_cells_0_exclude, nesting_cells_0_include) 
nesting_cells <- nesting_cells %>% arrange(Nest_ID, Date)
# remove and rename column
nesting_cells <- nesting_cells %>% select(-Nest_parasitized)
nesting_cells <- nesting_cells %>% rename(Nest_parasitized = Nest_parasitized_V2)


## Calculate how many nests are parasitized and make parasitized binary

# for all nests, take max number of cumulative parasites
 # Osmia
parasite_bin_os <- nesting_cells %>%
  filter(Status != 'empty' & Status != 'pseudo' & Occupant == 'osmia') %>%
  group_by(Nest_ID) %>%
  summarise(Max_par = max(Cumulative_par, na.rm = TRUE)) %>%
  mutate(Max_par = ifelse(is.infinite(Max_par), NA, Max_par))
# make binary column, parasitized or not  
parasite_bin_os <- parasite_bin_os %>% mutate(Nest_parasitized = if_else(Max_par == 0, 'no', 
                                                                   if_else(Max_par >= 1, 'yes', NA)))
table(parasite_bin_os$Nest_parasitized)
# 27 no and 54 yes 

 # Megachile
parasite_bin_meg <- nesting_cells %>%
  filter(Status != 'empty' & Status != 'pseudo' & Occupant == 'megachile') %>%
  group_by(Nest_ID) %>%  
  summarise(Max_par = max(Cumulative_par, na.rm = TRUE)) %>%
  mutate(Max_par = ifelse(is.infinite(Max_par), NA, Max_par))
# make binary column, parasitized or not  
parasite_bin_meg <- parasite_bin_meg %>% mutate(Nest_parasitized = if_else(Max_par == 0, 'no', 
                                                                   if_else(Max_par >= 1, 'yes', NA)))
table(parasite_bin_meg$Nest_parasitized)
# 43 no and 13 yes

# make binary sealed column 
nesting_cells <- nesting_cells %>% 
  mutate(Active_bin = if_else(Sealed == 'sealed', 0, if_else(Sealed == 'not sealed', 1, NA)))
# don't need to separate if inner walls are included or not, because we're using Active_bin for the parasite models, and parasites can't infect nests with no cell

# inspect
# nesting_cells_inspect <- nesting_cells %>% filter(Bee_choice == 1)


## Make column to say if nests are active enough to have mothers around

# within the unsealed nests, filter out ones that are abandoned 
# if nest is not sealed and says no change for 3-4 visits, it's abandoned

# make a column for nests that had cells and an end cap added. If nests had cells and end cap within the same field visit, we can assume that the female was active. If the nest had only an end cap, we won't count that as active.
nesting_cells <- nesting_cells %>% mutate(Active_and_end_caps = if_else(Sealed == 'sealed' & grepl('cell', Status), 'sealed but was active', 'other'))

# say abandoned or not
active_nests_summary <- nesting_cells %>%
  arrange(Trapnest, Nest_ID, Date) %>% # make sure data is ordered by date
  group_by(Trapnest, Nest_ID) %>%
  mutate( # check for 3 consecutive 'no change'
    three_no_change =
      Status == "no change" &
      lag(Status, 1) == "no change" &
      lag(Status, 2) == "no change",
    fourth_day_status = lead(Status, 1), # check if there's a fourth day
    Abandoned =
      three_no_change & # if there's 3 days of no change and the fourth day doesn't exist or there's no activity (end cap or cell) on the fourth day, say abandoned
      (
        is.na(fourth_day_status) |
        !grepl("end\\s*cap | cell", fourth_day_status)
      )
  )  %>%
  ungroup() %>%
  filter(Sealed == "not sealed" & Active_and_end_caps == "other" | Sealed == "sealed" & Active_and_end_caps == "sealed but was active" ) # filter this out last, otherwise it messes up nests that were sealed

# convert to 0s and 1s
active_nests_summary$Abandoned <- as.numeric(active_nests_summary$Abandoned)

  # Osmia
# sum the number of nests that are active and not abandoned for each trapnest date combination 
summ_active_os <- active_nests_summary %>% 
  filter(Abandoned != 1 & Sealed == 'not sealed' & Occupant == 'osmia' & Status != 'pseudo' | Active_and_end_caps == 'sealed but was active' & Occupant == 'osmia') %>% 
  group_by(Date, Trapnest) %>% 
  summarise(Osmia_active_mothers = length(unique(Nest_ID)))

# add to the full df
nesting_cells <- left_join(nesting_cells, summ_active_os)

# replace NAs with zero
nesting_cells <- nesting_cells %>%
  mutate(Osmia_active_mothers = replace_na(Osmia_active_mothers, 0))


  # Megachile
# sum the number of nests that are not abandoned for each trapnest date combination 
summ_active_meg <- active_nests_summary %>% 
  filter(Abandoned != 1 & Sealed == 'not sealed' & Occupant == 'megachile' & Status != 'pseudo'  | Active_and_end_caps == 'sealed but was active' & Occupant == 'megachile') %>% 
  group_by(Date, Trapnest) %>% 
  summarise(Meg_active_mothers = length(unique(Nest_ID)))

# add to the full df
nesting_cells <- left_join(nesting_cells, summ_active_meg)

# replace NAs with zero
nesting_cells <- nesting_cells %>%
  mutate(Meg_active_mothers = replace_na(Meg_active_mothers, 0))


## Make column for nests that never emerged with unknown parasitization status, to be used in NDP chunk
# is sealed or not sealed, but we don't have info if it parasitized or not because it never emerged, so say not parasitized, to be assumed that it was treated as a congeneric 

nesting_cells <- nesting_cells %>% mutate(Nest_parasitized_undev = if_else(!is.na(Sealed) & is.na(Nest_parasitized), 'not parasitized', Nest_parasitized))


```

```{r Parasite_Wrangling_for_Models}

# This chunk is to make columns needed for the models

# nesting df: nest-level, used to calculate trapnest summaries
# nesting_cell df: cell-level observations
# Par_nests_unsealed: number of parasitized unsealed nests per trapnest - date combo
# Par_total: total count of parasitized cells in a trapnest

# will have to make df with only nest-level observations to make summaries, then bind back together for cell-level models 
nesting_1 <- distinct(nesting_cells, Date, Nest_ID, .keep_all= TRUE) # for nest-level 
# remove cell-level columns
nesting_1 <- nesting_1 %>% select(-Cell_ID, -Cell_parasitized, -Cell_number, -Cell_position, -Cell_occupant, -Species_or_subtype)


## Count the number of unsealed nests
# I need all nests including pseudo (sealed and unsealed), all nests excluding pseudo (sealed and unsealed), which I already have (Osmia_ps_no_iw, etc) and only unsealed nests (and no pseudo nests are unsealed), which I calculate here. 
# Because I'm looking at parasites, I need the total values, not the prior values. E.g., how many existing nests are there in a trapnest when a parasite decides to lay an egg. So, there's no focal nest that would be excluded for models from the parasites perspective

# make a column to count number of unsealed nests for conspecifics 
# Osmia
unsealed_summary_os <- nesting_1 %>% 
  filter(Occupant == 'osmia' & Status != 'pseudo') %>% 
  group_by(Trapnest, Date) %>% 
  summarise(Sum_unsealed_os = sum(Active_bin, na.rm = T)) 
# Megachile
unsealed_summary_meg <- nesting_1 %>% 
  filter(Occupant == 'megachile' & Status != 'pseudo') %>% 
  group_by(Trapnest, Date) %>% 
  summarise(Sum_unsealed_meg = sum(Active_bin, na.rm = T)) 

nesting_1 <- full_join(nesting_1, unsealed_summary_os)
nesting_1 <- full_join(nesting_1, unsealed_summary_meg)
# NAs are normal for when there were no parasite attacks 


## Make data frame for cell-level observations for Osmia and Megachile
nesting_cells_os_0 <- nesting_cells %>% filter(!is.na(Cell_ID) & Occupant == 'osmia')
nesting_cells_meg_0 <- nesting_cells %>% filter(!is.na(Cell_ID) & Occupant == 'megachile')


# merge summary with new columns we made for models for preferences of parasite (excludes inner wall only) and bees (includes inner wall only)
length(unique(nesting_cells_os_0$Cell_ID)) # 749 cells, so we need a df of that length
nesting_cells_os_0 <- inner_join(nesting_cells_os_0, unsealed_summary_os)

length(unique(nesting_cells_meg_0$Cell_ID)) # 424 cells
nesting_cells_meg_0 <- inner_join(nesting_cells_meg_0, unsealed_summary_meg)

# check for duplicates
nesting_cells_os_0[duplicated(nesting_cells_os_0$Cell_ID),] 
nesting_cells_meg_0[duplicated(nesting_cells_meg_0$Cell_ID),] 


## Making day of the year
nesting_cells_os <- nesting_cells_os_0 %>% mutate(Day_of_year = lubridate::yday(as.Date(Date,format='%d/%m/%Y')))
nesting_cells_meg <- nesting_cells_meg_0 %>% mutate(Day_of_year = lubridate::yday(as.Date(Date,format='%d/%m/%Y')))
nesting_1 <- nesting_1 %>% mutate(Day_of_year = lubridate::yday(as.Date(Date,format='%d/%m/%Y')))

```

```{r Inspecting}


# inspect trapnests to see if the columns are correct. Here are some busy ones with meg and osmia, inner walls only, parasitezed and not, etc.

# Trapnest_87 <- nesting_1 %>% filter(Trapnest == 'trapnest_87')
# Trapnest_2 <- nesting_1 %>% filter(Trapnest == 'trapnest_2')
# Trapnest_17 <- nesting_1 %>% filter(Trapnest == 'trapnest_17')


```

```{r Detectable_and_No_Detectable_Parasites}


# In order to measure nesting preferences of bees to see if affected by parasites, I need to separate the nests with detectable parasites (DP) from the nests with no detectable parasites (NDP)
# this is about to get messy, so I'm making a smaller df 
nesting_2 <- nesting_1 %>% select(Trapnest, Date, Nest_ID, Status, Occupant, Bee_choice, New_nests_os, New_nests_meg, Available_cavities_prior, Osmia_ps:Meg_no_ps, Osmia_active_mothers, Meg_active_mothers, Nest_parasitized, Nest_parasitized_undev, Active_bin) 

# first I make the columns with the total numbers for DP and NDP and NDP with pseudo nests, then I need to calculate the number of those three columns prior to the new bees nesting there. So if there was 1 or more new nests in DP or NDP(_ps), I calculate (total nests in that group - new nests) + (n-1)/2 for the group that the new nest is a part of. If there's new nests for the other group (e.g., new DP nest, but from the new NDP nest perspective), we do (total nests in that group - 1/2 * new nests).


# Step 1) Making nests with total detectable parasite (DP) nests

## Count the number of unsealed parasitized nests for trapnest-date combo
# first, count the parasizited and unsealed
nesting_2 <- nesting_2 %>% mutate(Par_and_unsealed_os = if_else(Occupant == 'osmia' & Active_bin == 1 & Nest_parasitized_undev == 'parasitized', 1, 0))
nesting_2 <- nesting_2 %>% mutate(Par_and_unsealed_meg = if_else(Occupant == 'megachile' & Active_bin == 1 & Nest_parasitized_undev == 'parasitized', 1, 0))

# having with and without inner wall doesn't matter because we're using these to count number of unsealed parasitized nests, and there are no cases where parasites occur with only inner walls

# then sum by trapnest - date combo
nesting_2 <- nesting_2 %>%
  group_by(Date, Trapnest) %>%
  mutate(DP_os_post = sum(Par_and_unsealed_os, na.rm=TRUE)) %>%
  ungroup()
nesting_2 <- nesting_2 %>%
  group_by(Date, Trapnest) %>%
  mutate(DP_meg_post = sum(Par_and_unsealed_meg, na.rm=TRUE)) %>%
  ungroup()
# DP_nests_os: number of nests that are unsealed and are parasitized, during my visit (totals including all new nests)


# Step 2) Making nests with total no detectable parasites without pseudo (NDP) nests

# first, count unsealed and not parasitized
nesting_2 <- nesting_2 %>% mutate(No_par_and_unsealed_os = if_else(Occupant == 'osmia' & Active_bin == 1 & Nest_parasitized_undev == 'not parasitized' | Occupant == 'osmia' & Active_bin == 1 & Status == 'inner wall', 1, 0))
nesting_2 <- nesting_2 %>% mutate(No_par_and_unsealed_meg = if_else(Occupant == 'megachile' & Active_bin == 1 & Nest_parasitized_undev == 'not parasitized' | Occupant == 'megachile' & Active_bin == 1 & Status == 'inner wall', 1, 0))

# second, count sealed, regardless of parasites
nesting_2 <- nesting_2 %>% mutate(Sealed_os = if_else(Occupant == 'osmia' & Active_bin == 0, 1, 0))
nesting_2 <- nesting_2 %>% mutate(Sealed_meg = if_else(Occupant == 'megachile' & Active_bin == 0, 1, 0))

# thirdy, sum by trapnest - date combo
nesting_2 <- nesting_2 %>%
  group_by(Date, Trapnest) %>%
  mutate(NDP_os_post = sum(No_par_and_unsealed_os, na.rm=TRUE) + sum(Sealed_os, na.rm=TRUE)) %>%
  ungroup()
nesting_2 <- nesting_2 %>%
  group_by(Date, Trapnest) %>%
  mutate(NDP_meg_post = sum(No_par_and_unsealed_meg, na.rm=TRUE) + sum(Sealed_meg, na.rm=TRUE)) %>%
  ungroup()
# NDP_nests_os: number of nests that are unsealed and not parasitized, or sealed, during my visit (totals including all new nests)


# Step 3) Making nests with total no detectable parasites with pseudo (NDP_ps) 

# already have the count of unsealed and not parasitized (No_par_and_unsealed_os)

# second, count sealed, including pseudo
nesting_2 <- nesting_2 %>% mutate(Sealed_os_ps = if_else(Occupant == 'osmia' & Active_bin == 0 | Occupant == 'osmia' & Status == 'pseudo', 1, 0))
nesting_2 <- nesting_2 %>% mutate(Sealed_meg_ps = if_else(Occupant == 'megachile' & Active_bin == 0 | Occupant == 'megachile' & Status == 'pseudo', 1, 0))

# thirdy, sum by trapnest - date combo
nesting_2 <- nesting_2 %>%
  group_by(Date, Trapnest) %>%
  mutate(NDP_ps_os_post = sum(No_par_and_unsealed_os, na.rm=TRUE) + sum(Sealed_os_ps, na.rm=TRUE)) %>%
  ungroup()
nesting_2 <- nesting_2 %>%
  group_by(Date, Trapnest) %>%
  mutate(NDP_ps_meg_post = sum(No_par_and_unsealed_meg, na.rm=TRUE) + sum(Sealed_meg_ps, na.rm=TRUE)) %>%
  ungroup()
# NDP_ps_os_post: number of nests that are unsealed and not parasitized, or sealed, including pseudo, during my visit (totals including all new nests)

# remove columns I don't need
nesting_2 <- nesting_2 %>% select(-Par_and_unsealed_os, -No_par_and_unsealed_os, -Sealed_os, -Sealed_os_ps)


# Step 4) Make nests with the number of new nests for DP

 # DP 
nesting_2 <- nesting_2 %>% mutate(DP_os_new = if_else(Bee_choice == 1 & Occupant == 'osmia' & Active_bin == 1 & Nest_parasitized_undev == 'parasitized', 1, 0))
nesting_2 <- nesting_2 %>% mutate(DP_meg_new = if_else(Bee_choice == 1 & Occupant == 'megachile' & Active_bin == 1 & Nest_parasitized_undev == 'parasitized', 1, 0))

nesting_2 <- nesting_2 %>%
  group_by(Date, Trapnest) %>%
  mutate(DP_os_new_nests = sum(DP_os_new, na.rm=TRUE)) %>%
  ungroup()
nesting_2 <- nesting_2 %>%
  group_by(Date, Trapnest) %>%
  mutate(DP_meg_new_nests = sum(DP_meg_new, na.rm=TRUE)) %>%
  ungroup()
# DP_os_new_nests: sum of the new DP nests for trapnest - date combination


# Step 5) Make nests with the number of new nests for NDP (and NDP_ps, since no pseudo nests are ever new nests)

# first, count unsealed and no parasites
nesting_2 <- nesting_2 %>% mutate(NDP_1_os_new = if_else(Bee_choice == 1 & Occupant == 'osmia' & Active_bin == 1 & Nest_parasitized_undev == 'not parasitized' | Bee_choice == 1 & Occupant == 'osmia' & Status == 'inner wall', 1, 0))
nesting_2 <- nesting_2 %>% mutate(NDP_1_meg_new = if_else(Bee_choice == 1 & Occupant == 'megachile' & Active_bin == 1 & Nest_parasitized_undev == 'not parasitized' | Bee_choice == 1 & Occupant == 'megachile' & Status == 'inner wall', 1, 0))

# second, sealed
nesting_2 <- nesting_2 %>% mutate(NDP_2_os_new = if_else(Bee_choice == 1 & Occupant == 'osmia' & Active_bin == 0, 1, 0))
nesting_2 <- nesting_2 %>% mutate(NDP_2_meg_new = if_else(Bee_choice == 1 & Occupant == 'megachile' & Active_bin == 0, 1, 0))

nesting_2 <- nesting_2 %>%
  group_by(Date, Trapnest) %>%
  mutate(NDP_os_new_nests = sum(NDP_1_os_new, na.rm=TRUE) + sum(NDP_2_os_new, na.rm=TRUE)) %>%
  ungroup()
nesting_2 <- nesting_2 %>%
  group_by(Date, Trapnest) %>%
  mutate(NDP_meg_new_nests = sum(NDP_1_meg_new, na.rm=TRUE) + sum(NDP_2_meg_new, na.rm=TRUE)) %>%
  ungroup()
# NDP_os_new_nests: sum of the new NDP nests for trapnest - date combination


# Step 6) make the calculations for when one new nest is added 

# when there's 1 new nest, we remove 1 from the total (_post) 
# when there are no new nests, keep regular number

nesting_2 <- nesting_2 %>% mutate(DP_os_one = if_else(DP_os_new_nests == 1, (DP_os_post - 1), 
                                                     if_else(DP_os_new_nests == 0, DP_os_post, NA)))
nesting_2 <- nesting_2 %>% mutate(NDP_os_one = if_else(NDP_os_new_nests == 1, (NDP_os_post - 1), 
                                                     if_else(NDP_os_new_nests == 0, NDP_os_post, NA)))
nesting_2 <- nesting_2 %>% mutate(NDP_ps_os_one = if_else(NDP_os_new_nests == 1, (NDP_ps_os_post - 1), 
                                                     if_else(NDP_os_new_nests == 0, NDP_ps_os_post, NA)))
nesting_2 <- nesting_2 %>% mutate(DP_meg_one = if_else(DP_meg_new_nests == 1, (DP_meg_post - 1), 
                                                     if_else(DP_meg_new_nests == 0, DP_meg_post, NA)))
nesting_2 <- nesting_2 %>% mutate(NDP_meg_one = if_else(NDP_meg_new_nests == 1, (NDP_meg_post - 1), 
                                                     if_else(NDP_meg_new_nests == 0, NDP_meg_post, NA)))
nesting_2 <- nesting_2 %>% mutate(NDP_ps_meg_one = if_else(NDP_meg_new_nests == 1, (NDP_ps_meg_post - 1), 
                                                     if_else(NDP_meg_new_nests == 0, NDP_ps_meg_post, NA)))

# DP_os_one: the prior value for DP_os when only 0 or 1 new nest was made 
# NDP_os_one: the prior value for NDP_os when only 0 or 1 new nest was made 
# NDP_ps_os_one: the prior value for NDP_ps_os when only 0 or 1 new nest was made 


# Step 7) make the calculations for when multiple new nests are added 

# total of DP or NDP - (1/2 * new DP or NDP nests)

nesting_2 <- nesting_2 %>% mutate(DP_mult_new_os = if_else(DP_os_new_nests > 1, (DP_os_post - (1/2 * DP_os_new_nests)), NA))
nesting_2 <- nesting_2 %>% mutate(NDP_mult_new_os = if_else(NDP_os_new_nests > 1, (NDP_os_post - (1/2 * NDP_os_new_nests)), NA))
nesting_2 <- nesting_2 %>% mutate(NDP_ps_mult_new_os = if_else(NDP_os_new_nests > 1, (NDP_ps_os_post - (1/2 * NDP_os_new_nests)), NA))
nesting_2 <- nesting_2 %>% mutate(DP_mult_new_meg = if_else(DP_meg_new_nests > 1, (DP_meg_post - (1/2 * DP_meg_new_nests)), NA))
nesting_2 <- nesting_2 %>% mutate(NDP_mult_new_meg = if_else(NDP_meg_new_nests > 1, (NDP_meg_post - (1/2 * NDP_meg_new_nests)), NA))
nesting_2 <- nesting_2 %>% mutate(NDP_ps_mult_new_meg = if_else(NDP_meg_new_nests > 1, (NDP_ps_meg_post - (1/2 * NDP_meg_new_nests)), NA))
# DP_mult_new_os: the average number of nests a new nests that DP or NDP nests would see. 
# NDP_mult_new_os: the average number of nests a new nests that DP or NDP nests would see. 
# NDP_ps_mult_new_os: the average number of nests a new nests that DP or NDP nests would see, when NDP includes pseudo


# Step 8) Create columns to use

# if theres 1 new nest of DP, use DP_os_one. If there's more than one new nest of DP, use DP_mult_new_os
# if theres 1 new nest of NDP, use NDP_os_one. If there's more than one new nest of NDP, use NDP_mult_new_os
# if theres 1 new nest of NDP, use NDP_ps_os_one. If there's more than one new nest of NDP, use NDP_ps_mult_new_os

nesting_2 <- nesting_2 %>% mutate(DP_os_prior = if_else(DP_os_new_nests <= 1, DP_os_one,
                                                       if_else(DP_os_new_nests > 1, DP_mult_new_os, NA)))
nesting_2 <- nesting_2 %>% mutate(NDP_os_prior = if_else(NDP_os_new_nests <= 1, NDP_os_one,
                                                       if_else(NDP_os_new_nests > 1, NDP_mult_new_os, NA)))
nesting_2 <- nesting_2 %>% mutate(NDP_ps_os_prior = if_else(NDP_os_new_nests <= 1, NDP_ps_os_one,
                                                       if_else(NDP_os_new_nests > 1, NDP_ps_mult_new_os, NA)))
nesting_2 <- nesting_2 %>% mutate(DP_meg_prior = if_else(DP_meg_new_nests <= 1, DP_meg_one,
                                                       if_else(DP_meg_new_nests > 1, DP_mult_new_meg, NA)))
nesting_2 <- nesting_2 %>% mutate(NDP_meg_prior = if_else(NDP_meg_new_nests <= 1, NDP_meg_one,
                                                       if_else(NDP_meg_new_nests > 1, NDP_mult_new_meg, NA)))
nesting_2 <- nesting_2 %>% mutate(NDP_ps_meg_prior = if_else(NDP_meg_new_nests <= 1, NDP_ps_meg_one,
                                                       if_else(NDP_meg_new_nests > 1, NDP_ps_mult_new_meg, NA)))

# take columns I want
nesting_3 <- nesting_2 %>% select(Trapnest:Nest_parasitized_undev, DP_os_prior:NDP_ps_meg_prior)
# join with rest of df
nesting_3 <- left_join(nesting_1, nesting_3)
# remove unwanted columns again
nesting_3 <- nesting_3 %>% select(Site, Subsite, Trapnest, Treatment, Straw_ID, Date, Day_of_year, Filled_length_mm, Straw_length_mm, Nest_ID, Status, Sealed, Nest_parasitized, Nest_parasitized_undev, Occupant:New_nests_meg, Available_cavities_prior, New_nests_sum, Osmia_ps_prior:Meg_no_ps_prior, Osmia_active_mothers, Meg_active_mothers, Sum_unsealed_os, Sum_unsealed_meg, DP_os_prior:NDP_ps_meg_prior)

# testing out some instances 
# Trapnest_1 <- nesting %>% filter(Trapnest == 'trapnest_1' & Date == '2023-05-29')
# Trapnest_36 <- nesting %>% filter(Trapnest == 'trapnest_36' & Date == '2023-06-04') 
# Trapnest_87 <- nesting %>% filter(Trapnest == 'trapnest_87' & Date == '2024-07-26') 

```

```{r Inner_Wall_Only}


## How many nests have ever had only an inner wall?

# includes 'inner wall started' from earlier 

# take nests that have never had any cells 
inner_wall_pref <- preferences %>%
  group_by(Nest_ID) %>%
  filter(Status != 'empty' & Status != 'pseudo') %>% 
  filter(all(Contains_cells == 0))  

inner_wall_pref %>%
  group_by(Occupant) %>%
  summarise(n_unique_nests = n_distinct(Nest_ID))
# 5 megachile only inner walls and 22 osmia

inner_wall_summary <- inner_wall_pref %>% select(Date, Nest_ID, Occupant)
length(unique(inner_wall_summary$Nest_ID)) # 27 
inner_wall_summary <- inner_wall_summary %>%
  arrange(Nest_ID, Date) %>%   
  distinct(Nest_ID, .keep_all = TRUE)

# include nests that were ever only inner walls started to be built, but the abandoned 
# check to see if the lists of inner wall started nests ever went on to become nests after 
inner_wall_started_progress_2023 <- preferences %>%
  filter(Nest_ID %in% inner_wall_started_2023_1$Nest_ID & Status != 'empty' & Status !=  'no change')
length(unique(inner_wall_started_2023_1$Nest_ID)) # 25 
# remove if they progressed
inner_wall_started_2023 <- inner_wall_started_2023_1 %>%
  filter(
    !Nest_ID %in% inner_wall_started_progress_2023$Nest_ID & 
      (Occupant == 'osmia' | Occupant == 'megachile')
    )
length(unique(inner_wall_started_2023$Nest_ID)) # 2 megachile, 7 osmia 

# check for progress
inner_wall_started_progress_2024 <- preferences %>%
  filter(Nest_ID %in% inner_wall_started_2024_1$Nest_ID & Status != 'empty' & Status !=  'no change')
length(unique(inner_wall_started_2024_1$Nest_ID)) # 19 
# remove if they progressed
inner_wall_started_2024 <- inner_wall_started_2024_1 %>%
  filter(
    !Nest_ID %in% inner_wall_started_progress_2024$Nest_ID &
    (Occupant == 'osmia' | Occupant == 'megachile')
  )
length(unique(inner_wall_started_2024$Nest_ID)) # 6 megachile, 1 osmia

# merge together the inner wall only and started dfs
inner_wall_started_2023 <- inner_wall_started_2023 %>% select(Date, Nest_ID, Occupant)
inner_wall_started_2024 <- inner_wall_started_2024 %>% select(Date, Nest_ID, Occupant)
inner_wall_started <- rbind(inner_wall_started_2023, inner_wall_started_2024)
inner_wall_only_and_started <- rbind(inner_wall_started, inner_wall_summary)


# make occupant in nesting the same as inner_wall_only_and_started, because the inner wall started are considered empty (thus the occupant is 'none')

nesting_3 <- nesting_3 %>%
  left_join(
    inner_wall_only_and_started %>%
      select(Nest_ID, Date, Occupant_inner = Occupant),
    by = c('Nest_ID', 'Date')
  ) %>%
  mutate(
    Occupant = if_else(
      Occupant == 'none' & !is.na(Occupant_inner),
      Occupant_inner,
      Occupant
    )
  ) %>%
  select(-Occupant_inner)


# based on this small df, make new column to incidcate these are abandoned or not
# for the preferences df, make only the decidison to nest and continue building a zero (aka bee choice == 1 but for nest that eventually had cells)
nesting <- nesting_3 %>%
  arrange(Nest_ID, Date) %>%
  group_by(Nest_ID) %>%
  mutate(
    Abandoned_inner_wall_1 = if_else(
      !Nest_ID %in% inner_wall_only_and_started$Nest_ID &
        Status != 'empty' &
        Status != 'pseudo' &
        row_number() == (if (any(Status != 'empty' & Status != 'pseudo')) 
                           which(Status != 'empty' & Status != 'pseudo')[1] 
                         else NA), 0, NA)) %>%
  ungroup()
# add second column for the 1s
nesting <- nesting %>%
  arrange(Nest_ID, Date) %>%
  group_by(Nest_ID) %>%
  mutate(
    Abandoned_inner_wall = if_else(
      paste(Nest_ID, Date) %in% 
        paste(inner_wall_only_and_started$Nest_ID, inner_wall_only_and_started$Date),
      1, Abandoned_inner_wall_1))
# remove Abandoned_inner_wall_1
nesting <- nesting %>% 
  ungroup() %>% 
  select(-Abandoned_inner_wall_1)

table(nesting$Abandoned_inner_wall)
# 280 were built, 43 abandoned 
# remember, this includes 'inner walls started' that were considered empty so there are additional nests that don't count towards the total

```

```{r Active_Mothers_For_Bee_Models}

## Make column to say if nests are active enough to have mothers around for the bee models

# already done in nesting df

# make prior values


df_trap13 <- nesting_x %>% filter(Date == '2023-06-02' & Trapnest == 'trapnest_13')






# 1- for 0 or 1 new nests, (available_post - new nests) 
  # osmia  
nesting_x <- nesting %>% mutate(Osmia_active_mothers_prior_V1 = ifelse(Osmia_active_mothers == 1 & New_nests_os == 1, (Osmia_active_mothers - New_nests_os),
                                                                       ifelse(Osmia_active_mothers == 0, 0, 'TBD')))
  

# 2 A- for multiple new nests, (n-1)/2
  # osmia
nesting_x <- nesting_x %>% mutate(Osmia_active_equ = if_else(New_nests_os > 1, ((New_nests_os - 1)/2), NA))





# B- add equation + (active mothers - new nests)
  # osmia 
nesting_x <- nesting_x %>% mutate(Osmia_active_mothers_prior = ifelse(Osmia_active_mothers_prior_V1 == 'TBD', (Osmia_active_mothers - New_nests_os + Osmia_active_equ), 'leftover'))
                                      





```

```{r Editing_Data_for_Models}

# check structure
str(nesting)  

# add year
nesting <- nesting %>% 
  mutate(Year = if_else(Subsite %in% c('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X'), 'year_2023', 'year_2024'))
nesting_cells_os <- nesting_cells_os %>% 
  mutate(Year = if_else(Subsite %in% c('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X'), 'year_2023', 'year_2024'))
nesting_cells_meg <- nesting_cells_meg %>% 
  mutate(Year = if_else(Subsite %in% c('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X'), 'year_2023', 'year_2024'))

# make numeric
nesting$Straw_length_mm <- as.numeric(nesting$Straw_length_mm)
nesting$Filled_length_mm <- as.numeric(nesting$Filled_length_mm)

# round to nearest integer
nesting$Straw_length <- round(nesting$Straw_length_mm)
nesting$Filled_length <- round(nesting$Filled_length_mm)
nesting <- nesting %>% select(-Filled_length_mm, -Straw_length_mm)

# make binary
nesting_cells_os <- nesting_cells_os %>% mutate(Cell_position_bi = if_else(Cell_position == 'last cell', 1,
                                                     if_else(Cell_position == 'not last cell', 0, NA)))

nesting_cells_meg <- nesting_cells_meg %>% mutate(Cell_position_bi = if_else(Cell_position == 'last cell', 1,
                                                     if_else(Cell_position == 'not last cell', 0, NA)))


## Make df for just nest investment
nesting_investment_0 <- nesting %>% filter(Occupant!= 'none' & Status != 'pseudo' & Status != 'empty')

nesting_investment_0 <- nesting_investment_0 %>%
  arrange(Date, Nest_ID) %>%
  filter(Status != 'no change') %>% 
  # then for each Nest_ID, pick the earliest date
  group_by(Nest_ID) %>%
  slice_max(Date, with_ties = FALSE) %>%
  ungroup()

nesting_investment_0 <- nesting_investment_0 %>% filter(!is.na(Filled_length))
table(nesting_investment_0$Occupant) # 260
length(unique(nesting_investment_0$Nest_ID))
# 123 megachile, 137 osmia

# fitler out all nests that aren't end capped to exclude abandoned nests and nests not finished at the end of the experiment 
nesting_investment <- nesting_investment_0 %>% filter(Sealed == 'sealed')

# how many are left?
table(nesting_investment$Occupant)
# 61 megachile, 109 osmia

## Separate Osmia and Megachile data frames 
nesting_investment_os <- nesting_investment %>% filter(Occupant == 'osmia')
table(nesting_investment_os$Occupant) # 108
nesting_investment_meg <- nesting_investment %>% filter(Occupant == 'megachile') 
table(nesting_investment_meg$Occupant) # 61

# take only columns that make sense at the nest level
nesting <- nesting %>% select(Site, Subsite, Trapnest, Treatment, Nest_ID, Date, Day_of_year, Year, Status, Occupant, Sealed, Nest_parasitized, Nest_parasitized_undev, Good_days, Bee_choice, Available_post, New_nests_os, New_nests_meg, New_nests_sum, Available_cavities_prior, Osmia_ps_prior, Osmia_no_ps_prior, Meg_ps_prior, Meg_no_ps_prior, Sum_unsealed_os, Sum_unsealed_meg, DP_os_prior, NDP_os_prior, NDP_ps_os_prior, DP_meg_prior, NDP_meg_prior, NDP_ps_meg_prior, Abandoned_inner_wall)

# still has duplicates for the nests, and seperate os and meg 
nesting_os <- nesting %>% filter(Occupant == 'osmia' | Occupant == 'none')
nesting_meg <- nesting %>% filter(Occupant == 'megachile' | Occupant == 'none')

# remove non-target columns
nesting_os <- nesting_os %>% select(-New_nests_meg, -Meg_ps_prior, -Meg_no_ps_prior, -Sum_unsealed_meg, -DP_meg_prior, -NDP_meg_prior, -NDP_ps_meg_prior)

nesting_meg <- nesting_meg %>% select(-New_nests_os, -Osmia_ps_prior, -Osmia_no_ps_prior, -Sum_unsealed_os, -DP_os_prior, -NDP_os_prior, -NDP_ps_os_prior)


# is the math adding up? should be 43
table(nesting_os$Abandoned_inner_wall) # 30
table(nesting_meg$Abandoned_inner_wall) # 13

# parasite data already only for collected nests
table(nesting_investment$Date)

# counting new nests 
nesting_os %>% filter(!is.na(Bee_choice)) %>% 
  summarize(nests_total = sum(Bee_choice)) # 167 osmia nests 
nesting_meg %>% filter(!is.na(Bee_choice)) %>% 
  summarize(nests_total = sum(Bee_choice)) # 140 megachile nests 
nesting %>% filter(!is.na(Bee_choice)) %>% 
  summarize(nests_total = sum(Bee_choice)) # 307 total


## Summing by trapnest

# remove duplicates of date-trapnest combo
trapnesting_os <- distinct(nesting_os, Date, Trapnest, .keep_all= TRUE)
trapnesting_meg <- distinct(nesting_meg, Date, Trapnest, .keep_all= TRUE)

# take only columns that make sense at the trapnest level
trapnesting_os <- trapnesting_os %>% select(Trapnest, Date, Day_of_year, Year, Site, Subsite, Treatment, Good_days, New_nests_os, New_nests_sum, Available_cavities_prior, Osmia_ps_prior, Osmia_no_ps_prior, Sum_unsealed_os, DP_os_prior, NDP_os_prior, NDP_ps_os_prior)

trapnesting_meg <- trapnesting_meg %>% select(Trapnest, Date, Day_of_year, Year, Site, Subsite, Treatment, Good_days, New_nests_meg, New_nests_sum, Available_cavities_prior, Meg_ps_prior, Meg_no_ps_prior, Sum_unsealed_meg, DP_meg_prior, NDP_meg_prior, NDP_ps_meg_prior)

# still the same as before
trapnesting_os %>% 
  summarize(nests_total = sum(New_nests_os)) # 167 osmia nests 
trapnesting_meg %>% 
  summarize(nests_total = sum(New_nests_meg)) # 140 megachile nests 

#remove NAs from emergence data for analyses 
nesting_cells_os <- nesting_cells_os %>% filter(!is.na(Cell_parasitized))
nesting_cells_meg <- nesting_cells_meg %>% filter(!is.na(Cell_parasitized))

## Saving wrangled data

  # nest-level data for all cavities
write.csv(nesting_os, 'data/nesting_cleaned_osmia.csv')
write.csv(nesting_meg, 'data/nesting_cleaned_megachile.csv')
  # trapnest-level data
write.csv(trapnesting_os, 'data/trapnesting_cleaned_osmia.csv')
write.csv(trapnesting_meg, 'data/trapnesting_cleaned_megachile.csv')
  # nest-level data for investment measures
write.csv(nesting_investment_os, 'data/investment_cleaned_osmia.csv')
write.csv(nesting_investment_meg, 'data/investment_cleaned_megachile.csv')
  # cell-level data
write.csv(nesting_cells_os, 'data/nesting_cells_cleaned_osmia.csv')
write.csv(nesting_cells_meg, 'data/nesting_cells_cleaned_megachile.csv')


```

```{r Descriptive}


## How long are the straws?
mean(nesting_investment$Straw_length) # 140.7 
sd(nesting_investment$Straw_length) # 9.7 


## How many instances were both of the rarest sized cavities occupied at the same time?
rare_df <- preferences_1 %>%
  filter((Trapnest %in% paste0('trapnest_', 1:36) & Cavity_size == 'large') |
         (Trapnest %in% paste0('trapnest_', 37:108) & Cavity_size == 'small'))

rare_df_filtered <- rare_df %>%
  group_by(Trapnest, Date) %>%
  filter(!any(Status == 'empty')) %>%
  ungroup()

rare_df_filtered %>%
  distinct(Trapnest, Date) %>%
  nrow() # 100 days and trapnest combinations that have both rare holes filled

preferences_1 %>%
  filter(Status != 'non_existent') %>% 
  distinct(Trapnest, Date) %>%
  nrow() # out of the 2214 days and trapnest combinations 
# (100/2214) * 100 so 4.5% of the time


## Verifying my treatments: How related are my treatments to the number of available cavities?
confirm_treatment_data <- nesting %>%
  distinct(Treatment, Subsite, Day_of_year, .keep_all = TRUE)
# mean and SD
confirm_treatment_data %>% 
  group_by(Treatment) %>% 
  summarise(Mean_avail = mean(Available_cavities_prior),
            SD_avail = sd(Available_cavities_prior))
  # Mean +- SD
   # Low-occupancy = 17.4 +- 1.0
   # Mid-occupancy = 11.6 +- 0.9
   # High-occupancy = 6.7 +- 0.8

# range of available cavities
confirm_treatment_data %>% 
  filter(Treatment == 'Low') %>% 
  ungroup() %>%
  summarise(Min_low = min(Available_cavities_prior),
            Max_low = max(Available_cavities_prior)) # 12, 18
confirm_treatment_data %>% 
  filter(Treatment == 'Mid') %>% 
  ungroup() %>%
  summarise(Min_mid = min(Available_cavities_prior),
            Max_mid = max(Available_cavities_prior)) # 5, 13
confirm_treatment_data %>% 
  filter(Treatment == 'High') %>% 
  ungroup() %>%
  summarise(Min_high = min(Available_cavities_prior),
            Max_high = max(Available_cavities_prior)) # 1, 9


## How many nests per year?
nesting %>% 
  group_by(Occupant, Year) %>% 
  filter(Occupant != 'none') %>% 
  summarise(Nests = sum(!is.na(Bee_choice)))
#             2023  2024 
# Osmia       162   5
# Megachile   64    76


## How many nests were excluded from investment?
nesting_investment_0 %>%
  filter(Sealed != "sealed") %>%
  count(Occupant)
# Megachile    62
# Osmia        28



## How many nests were not developed?
nesting_cells %>% 
  filter(!is.na(Nest_parasitized_undev)) %>% 
  group_by(Nest_parasitized_undev, Occupant) %>% 
  summarise(count = length(unique(Nest_ID)))
#                   Osmia  Megachile 
# not parasitized    128    129
# parasitized        55     14

nesting_cells %>% 
  filter(!is.na(Nest_parasitized)) %>% 
  group_by(Nest_parasitized, Occupant) %>% 
  summarise(count = length(unique(Nest_ID)))
#                   Osmia  Megachile 
# not parasitized    65     55
# parasitized        55     14


## Ever more than one parasite type per nest?
nesting_cells_os %>%
  filter(Cell_occupant == "parasite") %>%
  group_by(Nest_ID) %>%
  summarise(n_species = n_distinct(Species_or_subtype)) %>%
  filter(n_species > 1) # none

nesting_cells_meg %>%
  filter(Cell_occupant == "parasite") %>%
  group_by(Nest_ID) %>%
  summarise(n_species = n_distinct(Species_or_subtype)) %>%
  filter(n_species > 1) # none


## What was the development percentage? AKA the number of cells that had an identifyable occupant
nesting_cells %>% 
  filter(!is.na(Cell_ID)) %>% 
  group_by(Cell_occupant) %>% 
  summarise(count = length(unique(Cell_ID)))
# empty	        52			
# megachile	    122			
# mold	        114			
# osmia	        180			
# parasite    	134			
# pollen       	277			
# unknown larva	305			
(122 + 180 + 134) / (122 + 180 + 134 + 52 + 114 + 277 + 305) # 37% 


## Species count for developed cells 
table_species <- nesting_cells %>%
  filter(Cell_occupant == 'megachile' & !is.na(Species_or_subtype) | Cell_occupant == 'osmia' & !is.na(Species_or_subtype)) %>%
  count(Species_or_subtype)
# 1 Megachile centuncularis
# 1 Megachile mendica
# 32 Megachile pugnata
# 77 Megachile relativa
# 1 Megachile rountundata
# 80 Osmia pumila
# 49 Osmia tersula

## Species count for nests
counting_species_by_nest <- nesting_cells %>%
  filter(Cell_occupant == 'megachile' & !is.na(Species_or_subtype) | Cell_occupant == 'osmia' & !is.na(Species_or_subtype)) %>% 
  group_by(Nest_ID) %>%
  count(Species_or_subtype)

counting_species_by_nest <- counting_species_by_nest %>% 
  group_by(Species_or_subtype) %>% 
  summarise(count = length(unique(Nest_ID)))
# Megachile centuncularis	 1			
# Megachile mendica	       1			
# Megachile pugnata	       20			
# Megachile relativa	     20			
# Megachile rotundata	     1	
# Osmia pumila	           27		
# Osmia tersula	           19	

```

```{r Example_Code}
 
# Testing to make sure my looping method works 

# # loop takes too long to do at once
# # so remove all empty and pseudo, then adding back in after
# # test it with trapnest 12 first
# emerg_and_pref_ex1 <- emerg_and_pref %>% filter(Trapnest== 12) # including empty and pseudo
# emerg_and_pref_ex2 <- emerg_and_pref %>% filter(Trapnest== 12 & Status != 'empty' & Status != 'pseudo') # excluding empty and pseudo
# 
# # Test 1
# for(i in 1:nrow(emerg_and_pref_ex1)){
#   nestID <- emerg_and_pref_ex1$Nest_ID[i] # focal nest for i-th row
#   dt <- emerg_and_pref_ex1$Date[i] # date for i-th row
#   allprev <- emerg_and_pref_ex1 %>% filter(Nest_ID == nestID & Date <= dt) %>% pull(Cumulative_par_max) # all previous parasite counts for that focal nest
#   
#   check1 <- !all(is.na(allprev))
#   check2 <- !emerg_and_pref_ex1$Status[i] %in% c('empty', 'pseudo') 
#   # you'll have to adjust this as needed for the intended behaviour & possible values in your larger dataset
#   
#   if(check1 & check2){
#     emerg_and_pref_ex1$Cumulative_par_V2[i] <- max(allprev, na.rm = T)
#   }
# }
# view(emerg_and_pref_ex1) # looks good
# 
# # Test 2
# for(i in 1:nrow(emerg_and_pref_ex2)){
#   nestID <- emerg_and_pref_ex2$Nest_ID[i] # focal nest for i-th row
#   dt <- emerg_and_pref_ex2$Date[i] # date for i-th row
#   allprev <- emerg_and_pref_ex2 %>% filter(Nest_ID == nestID & Date <= dt) %>% pull(Cumulative_par_max) # all previous parasite counts for that focal nest
#   
#   check1 <- !all(is.na(allprev))
#   check2 <- !emerg_and_pref_ex2$Status[i] %in% c('empty', 'pseudo') 
#   # you'll have to adjust this as needed for the intended behaviour & possible values in your larger dataset
#   
#   if(check1 & check2){
#     emerg_and_pref_ex2$Cumulative_par_V2[i] <- max(allprev, na.rm = T)
#   }
# }
# view(emerg_and_pref_ex2) # looks good
# # bind back together
# emerg_and_pref_ex3 <- emerg_and_pref %>% filter(Trapnest== 12 & Status == 'empty' | Trapnest== 12 & Status == 'pseudo') # the empty and pseudo ones
# # the length of ex1 should = ex2 + ex3 --> 80 + 334 
# emerg_and_pref_ex3 <- rbind(emerg_and_pref_ex2, emerg_and_pref_ex3)
# emerg_and_pref_ex3 <- emerg_and_pref_ex3 %>% arrange(Nest_ID, Date)

```
