---
title: "Analyses"
format: html
editor: visual
---

------------------------------------------------------------------------

## Statistical Models

Variables:

-   Nest_ID: the trapnest number, cavity number, and straw ID put together. Unique for each nest.
-   Index: you can ignore this. It gave every row a unique number that I needed for a loop.
-   Status: the activity of that cavity, e.g., its empty, new cells are made, a nest is sealed off, etc.
-   **Bee_choice**: is a new nest built or not, Yes = 1, no = 0, pseudo nests or nests already in progress or completed get an NA.
-   Available_post: number of available cavities for each trapnest and date combo AFTER the new nests for that visit have been started (i.e., how many available cavities that the experiments saw when arriving to the nest)
-   New_nests_os: number of new osmia nests for each trapnest and date combo
-   **Osmia_ps_prior**: number of existing osmia in each trapnest per date, including pseudo nests
-   **Osmia_no_ps_prior**: number of existing osmia in each trapnest per date, excluding pseudo nests
-   New_nests_meg: number of new megachile nests for each trapnest and date combo
-   **Meg_ps_prior**: number of existing megachile in each trapnest per date, including pseudo nests
-   **Meg_no_ps_prior**: number of existing megachile in each trapnest per date, excluding pseudo nests
-   New_nests_sum: total number of new nests including megachile and osmia.
-   **Available_prior**: average number of available cavities for each trapnest and date combo BEFORE the new nests for that visit have been started (i.e., how many available cavities the bees saw when arriving to the nest before building). This is the average, so there are some numbers that have .5 in there. For example, if there are 8 cavities available_post and two new nests were built when we visited that trapnest, the first bee to nest would have seen 10 available cavities, and the second would have seen 9. So we average that out to 9.5 for available_prior.
-   **Par_in_trapnest**: number of parasites present in the trapnest when I log new bee nests (Bee_choice).
-   **Prop_filled**: proportion of the straw filled with cells, used as a measure of investment into a nest.

```{r Prep}

## Loading data and packages

library(glmmTMB)
library(DHARMa)
library(lme4)
library(car)
library(see)
library(performance)
library(ggeffects)
library(tidyverse)

nesting <- read_csv('data/nesting_cleaned_all_bees.csv')
nesting_os <- read_csv('data/nesting_cleaned_osmia.csv')
nesting_meg <- read_csv('data/nesting_cleaned_megachile.csv') # three columns with parasite and cell info blank, not dissected
nesting_os_xs <- read_csv('data/nesting_cleaned_osmia_xs.csv')
nesting_meg_xs <- read_csv('data/nesting_cleaned_megachile_xs.csv')
investment <- read_csv('data/investment_cleaned.csv')
investment_os <- investment %>% filter(Occupant == 'osmia')

```

### Nesting per Available Cavities

```{r Models: Nest per Available Cavities}


# MODEL 1 
### New nests per available cavities Osmia ###
mod_choice_cav_os <- glmer(New_nests_os ~ scale(Available_cavities_prior) + scale(Good_days) + scale(Day_of_year) + Site + (1|Trapnest), data = nesting_os_xs, family = poisson) # + (1| dummy)

plot(simulateResiduals(mod_choice_cav_os)) ## ERROR ##
testDispersion(mod_choice_cav_os, type = 'DHARMa') 
testZeroInflation(mod_choice_cav_os)
testOutliers(mod_choice_cav_os, type = 'bootstrap') ## issues?
check_model(mod_choice_cav_os) ## yikes 
summary(mod_choice_cav_os)
save(mod_choice_cav_os, file='mod_choice_cav_os.Rdata') # save models

# Plot model
ggpredict(mod_choice_cav_os, c('Available_cavities_prior')) %>% plot(rawdata = TRUE, jitter = .04) + labs(x = 'Available cavities', y = 'Presence of new nest for each visit', title = 'Osmia: available cavities')


# MODEL 2
### New nests per available cavities Megachile ###
mod_choice_cav_meg <- glmer(cbind(New_nests_meg/Available_cavities_prior) ~ Available_cavities_prior + Good_days + Day_of_year + Site + (1|Subsite/Trapnest), data = nesting_meg_xs, family = binomial) 

plot(simulateResiduals(mod_choice_cav_meg)) 
testDispersion(mod_choice_cav_meg, type = 'DHARMa') 
testOutliers(mod_choice_cav_meg, type = 'bootstrap') 
check_model(mod_choice_cav_meg) ## yikes
summary(mod_choice_cav_meg) ## WRONG ##


# Plot model
ggpredict(mod_choice_cav_os, c('Available_cavities_prior')) %>% plot(rawdata = TRUE, jitter = .04) + labs(x = 'Available cavities', y = 'Presence of new nest for each visit')
check_model(mod_choice_cav_os)

```

### Nesting per Conspecific Presence

```{r Models: Nest per Conspecifics}


# MODEL 3 # OPTION A
### New nests per conspecifics Osmia, with pseudo ###

mod_choice_consp_os_ps <- glmer(New_nests_os ~ Osmia_ps_prior + Good_days + Day_of_year + Site + (1|Subsite/Trapnest), data = nesting_os_xs, family = poisson)

plot(simulateResiduals(mod_choice_consp_os_ps)) ## ERROR ## 
check_model(mod_choice_consp_os_ps) ## binned residuals and residual normality bad
testDispersion(mod_choice_consp_os_ps, type = 'DHARMa')  
testOutliers(mod_choice_consp_os_ps, type = 'bootstrap') 
testZeroInflation(mod_choice_consp_os_ps)
summary(mod_choice_consp_os_ps)


ggpredict(mod_choice_consp_os_ps, c('Osmia_ps_prior')) %>% plot(rawdata = TRUE, jitter = .04) 


# MODEL 3 # OPTION B
mod_choice_consp_os_ps_2 <- glm(log(New_nests_os) ~ offset(log(Available_cavities_prior)) + Osmia_ps_prior + Good_days + Day_of_year + Site + (1|Subsite/Trapnest), data = nesting_os_xs, family = poisson)
## ERROR ## "Error in Subsite/Trapnest : non-numeric argument to binary operator", then if thats removed "Error in eval(family$initialize) : negative values not allowed for the 'Poisson' family"




# MODEL 4 # OPTION A
### New nests per conspecifics Osmia, without pseudo ###

mod_choice_consp_os_no_ps <- glmer(New_nests_os ~ scale(Osmia_no_ps_prior) + scale(Good_days) + scale(Day_of_year) + Site + (1|Subsite/Trapnest), data = nesting_os_xs, family = poisson())

plot(simulateResiduals(mod_choice_consp_os_no_ps)) 
check_model(mod_choice_consp_os_no_ps) ## YIKES
testDispersion(mod_choice_consp_os_no_ps, type = 'DHARMa') # not a big deal, small
testOutliers(mod_choice_consp_os_no_ps, type = 'bootstrap') 
summary(mod_choice_consp_os_no_ps)


ggpredict(mod_choice_consp_os_no_ps, c('Osmia_no_ps_prior')) %>% plot(rawdata = TRUE, jitter = .04) 


# MODEL 5
### New nests per conspecifics Megachile, with pseudo ###
mod_choice_consp_meg_ps <- glmer(cbind(New_nests_meg/Available_cavities_prior) ~ Meg_ps_prior + Good_days + Day_of_year + Site + (1|Subsite/Trapnest), data = nesting_meg_xs, family = binomial)

plot(simulateResiduals(mod_choice_consp_meg_ps)) 
check_model(mod_choice_consp_meg_ps) 
testDispersion(mod_choice_consp_meg_ps, type = 'DHARMa') 
testOutliers(mod_choice_consp_meg_ps, type = 'bootstrap') 
summary(mod_choice_consp_meg_ps) ## WRONG ##


# MODEL 6
### New nests per conspecifics Megachile, without pseudo ###
mod_choice_consp_meg_no_ps <- glmer(cbind(New_nests_meg/Available_cavities_prior) ~ Meg_no_ps_prior + Good_days + Day_of_year + Site + (1|Subsite/Trapnest), data = nesting_meg_xs, family = binomial)

plot(simulateResiduals(mod_choice_consp_meg_no_ps)) 
check_model(mod_choice_consp_meg_no_ps) 
testDispersion(mod_choice_consp_meg_no_ps, type = 'DHARMa') 
testOutliers(mod_choice_consp_meg_no_ps, type = 'bootstrap') 
summary(mod_choice_consp_meg_no_ps) ## WRONG ##

```

------------------------------------------------------------------------

### Parasitism

```{r Parasitism Models}


# MODEL 7
# Relation between parasites and aggregation densities
# cell parasitized or not (cell level) ~ number of nests in the trapnest [sealed or not??] (trapnest level) + good days + day of year + site + (1|Subsite/Trapnest)




# MODEL 8
# How the presence of parasites effects nesting preferences
# number of new nests ~ parasites in unsealed nests (both trapnest level) + good days + day of year + site + (1|Subsite/Trapnest)



# MODEL 9
# How the presence of parasites effects nest investment
# proportion of straw filled [time?? just before sealed] (nest level) ~ number of parasites in unsealed nests (trapnest level) * target nests is parasitized (nest level) + good days + day of year + site + (1|Subsite/Trapnest) [whats the most extreme iapct of parasties? stop building after detect a cell is parasizitd]







```

### Investment

```{r Investment Models, include=FALSE, echo=TRUE, results='hide'}

library(betareg)

hist(investment_os$Prop_filled)

# MODEL 8
mod_invest_os <- glmer(Prop_filled ~ Par_in_trapnest * Cumulative_par + Day_of_year + Site + (1|Subsite/Cavity_ID), data = investment_os, family = binomial)

plot(simulateResiduals(mod_invest_os))
summary(mod_invest_os)





# 3) Do bees reduce investment in a nest if parasites are present?
# Proportion of volume filled with cells ~ presence of parasites in that trapnest * if the nest is parasitized or not + parasite species + (1|site/subsite/trapnest)



```

```{r Plotting Models}

# Plot models


ggpredict(mod_choice_consp_meg_no_ps, c('Available_prior')) %>% plot(rawdata = TRUE, jitter = .04)



# Plot actual model
ggpredict(mod_choice_cav_meg, c('Available_prior')) %>% plot(rawdata = TRUE, jitter = .04) + labs(x = 'Available cavities', y = 'Presence of new nest for each visit', title = 'Megachile: available cavities (full season)')


# Plot actual model
ggpredict(mod_choice_consp_os_ps, c('Osmia_ps_prior')) %>% 
  plot(rawdata = TRUE, jitter = .04) + 
  labs(x = 'Osmia occupancies including pseudo', y = 'Presence of new nest for each visit', title = 'Osmia') +
  xlim(0, 18)

```
