---
title: 'Nest-Site Selection in Non-Eusocial Cavity-Nesting Bees'
format: 
  html:
    self-contained: true
    toc: true
  docx: default
editor: visual
---

```{r Prepping, include=FALSE}

## Loading packages
library(ggplot2)
library(ggeffects)
library(kableExtra) 
library(lme4)
library(tidyverse)
library(patchwork)
library(gridExtra)
library(grid)
library(cowplot)


## Loading data
  # nest-level data for all cavities
nesting_os <- read_csv('data/nesting_cleaned_osmia.csv')
nesting_meg <- read_csv('data/nesting_cleaned_megachile.csv') 
  # trapnest-level data
trapnesting_os <- read_csv('data/trapnesting_cleaned_osmia.csv')
trapnesting_meg <- read_csv('data/trapnesting_cleaned_megachile.csv')
  # cell-level data
nesting_cells_os <- read_csv('data/nesting_cells_cleaned_osmia.csv')
nesting_cells_meg <- read_csv('data/nesting_cells_cleaned_megachile.csv')
  # nest-level data for investment measures
nesting_investment_os <- read_csv('data/investment_cleaned_osmia.csv')
nesting_investment_meg <- read_csv('data/investment_cleaned_megachile.csv')


# number of nests
nesting_os %>%
  filter(!is.na(Bee_choice)) %>%
  summarize(nests_total = sum(Bee_choice)) # 167 osmia nests for osmia through the summer
nesting_meg %>%
  filter(!is.na(Bee_choice)) %>%
  summarize(nests_total = sum(Bee_choice)) # 140 megachile nests for osmia through the summer

# set theme
theme_set(theme_classic(base_size = 15))


## Cleaning data to match the data analysed
nesting_os <- nesting_os %>% filter(Year != 'year_2024')
trapnesting_os <- trapnesting_os %>% filter(Year != 'year_2024')
nesting_cells_os <- nesting_cells_os %>% filter(Year != 'year_2024')
nesting_investment_os <- nesting_investment_os %>% filter(Year != 'year_2024')
nesting_os <- nesting_os %>% filter(Site != 'CP')
trapnesting_os <- trapnesting_os %>% filter(Site != 'CP')
nesting_cells_os <- nesting_cells_os %>% filter(Site != 'CP')
nesting_meg <- nesting_meg %>% filter(Site != 'NN')
trapnesting_meg <- trapnesting_meg %>% filter(Site != 'NN')
nesting_cells_meg <- nesting_cells_meg %>% filter(Site != 'NN')



```

```{r Simulations, include=FALSE}


## Create the function to simulate data

# simulate the null hypothesis that bees are treating each cavity equally, thus nesting would be based just on availability
# simulation without replacement so that if there are multiple new osmia nests, the number of available cavities goes down by one for each sequential new nest in that subsite-group combo

# create a function to simulate the distribution of nests based on the null hypothesis that bees are nesting according to available cavities 
simulate_nests <- function(avail_cavities, total_nests) {
  n <- length(avail_cavities) # number of available cavities
  nest_counts <- rep(0, n) # start with zero nests in each trapnest

  # keep as zeros is no nests are built
  if (total_nests == 0) {
    return(nest_counts)
  }

  # look through each of the new nests to be randomly assigned
  for (i in 1:total_nests) {
    if (sum(avail_cavities) == 0) break  # stop if all cavities used
    probability <- avail_cavities / sum(avail_cavities) # calculate probability proportional to the number of available cavities
    chosen <- sample(1:n, size = 1, prob = probability) # randomly choose a trapnest for the new nest based on available cavities
    nest_counts[chosen] <- nest_counts[chosen] + 1 # record it
    avail_cavities[chosen] <- avail_cavities[chosen] - 1 # reduce the number of available cavities by 1, when we apply the function the loop will run again until no new nests are left
  }
  return(nest_counts) # return the vector with how many nests were randomly assigned
}

# indicate how many simulated data columns we want for the model
n_sim <- 100 


## Apply the function

trapnesting_os_null <- trapnesting_os %>%
  group_by(Subsite, Date) %>%
  group_modify(~ { # simulate random nest distribution for subsite-date combo
    for (i in 1:n_sim){ # make each of the columns we indicated that we want 
    nest_counts <- simulate_nests(.x$Available_cavities_prior, sum(.x$New_nests_os)) # use available cavities as weights and sum the new nests
    .x[[paste0('Null_new_nests', i)]] <- nest_counts # make the new column
    }
    .x # return the modified group
  }
  ) %>%
  ungroup()


## Apply the function

trapnesting_meg_null <- trapnesting_meg %>%
  group_by(Subsite, Date) %>%
  group_modify(~ { # simulate random nest distribution for subsite-date combo
    for (i in 1:n_sim){ # make each of the columns we indicated that we want 
    nest_counts <- simulate_nests(.x$Available_cavities_prior, sum(.x$New_nests_meg)) # use available cavities as weights and sum the new nests
    .x[[paste0('Null_new_nests', i)]] <- nest_counts # make the new column
    }
    .x # return the modified group
  }
  ) %>%
  ungroup()


```

```{r Ordering_treatments, include=FALSE}


## Ordering treatments
trapnesting_os_null$Treatment <- factor(trapnesting_os_null$Treatment, 
                                    levels = c('Low', 'Mid', 'High'))
trapnesting_meg_null$Treatment <- factor(trapnesting_meg_null$Treatment, 
                                    levels = c('Low', 'Mid', 'High'))

nesting_cells_os$Treatment <- factor(nesting_cells_os$Treatment, 
                                    levels = c('Low', 'Mid', 'High'))
nesting_cells_meg$Treatment <- factor(nesting_cells_meg$Treatment, 
                                    levels = c('Low', 'Mid', 'High'))

## Make mean of null new nests
trapnesting_os_null <- trapnesting_os_null %>% mutate(Null_new_nests_mean = rowMeans(select(., Null_new_nests1:Null_new_nests100)))
trapnesting_meg_null <- trapnesting_meg_null %>% mutate(Null_new_nests_mean = rowMeans(select(., Null_new_nests1:Null_new_nests100)))


```

## Congeneric Attraction

```{r P1_Congeneric_Attraction, echo=FALSE, warning=FALSE, message=FALSE}


## Osmia ##

# make proportion of new nests / available cavities
P1_os <- trapnesting_os_null %>% 
  select(Trapnest, Treatment, Date, New_nests_os, Available_cavities_prior, Null_new_nests_mean) %>% 
  group_by(Trapnest, Treatment) %>%
  summarise(sum_New_nests_os = sum(New_nests_os), sum_Available_cavities_prior = sum(Available_cavities_prior), sum_Null_new_nests_mean = sum(Null_new_nests_mean)) 

P1_os <- P1_os %>% 
  group_by(Trapnest, Treatment) %>% 
  summarise(Prop_new_of_avail_obs = (sum_New_nests_os/sum_Available_cavities_prior), Prop_new_of_avail_null = (sum_Null_new_nests_mean/sum_Available_cavities_prior))

# pivot longer
P1_os <- P1_os %>% 
  pivot_longer(
    cols = c('Prop_new_of_avail_obs', 'Prop_new_of_avail_null'),
    names_to = 'Data_type',
    values_to = 'Proportion'
  )

# make the mean and error bars
P1_os_sum <- P1_os %>%
  group_by(Treatment, Data_type) %>%
  summarise(
    Mean = mean(Proportion),
    SD = sd(Proportion), 
    SE = SD / sqrt(n()),
    CI_low = Mean - 1.96 * SE,
    CI_high = Mean + 1.96 * SE,
    .groups = 'drop'
  )


Fig_p1_os <- P1_os_sum %>%
  ggplot(aes(y = Mean, x = Treatment, fill = Data_type)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  geom_errorbar(aes(ymin = Mean - SE, ymax = Mean + SE),
                width = 0.3,
                position = position_dodge(width = 0.9)) +
  scale_fill_manual(
    values = c('Prop_new_of_avail_null' = '#F0C282',
      'Prop_new_of_avail_obs'  = '#59989e'),
    name = bquote(italic(Osmia) ~ 'Data'),
    breaks = c('Prop_new_of_avail_null', 'Prop_new_of_avail_obs'),
    labels = c('Simulated', 'Observed')
  ) +
  labs(y = NULL, x = NULL)



## Megachile ##

# make proportion of new nests / available cavities
P1_meg <- trapnesting_meg_null %>% 
  select(Trapnest, Treatment, Date, New_nests_meg, Available_cavities_prior, Null_new_nests_mean) %>% 
  group_by(Trapnest, Treatment) %>%
  summarise(sum_New_nests_meg = sum(New_nests_meg), sum_Available_cavities_prior = sum(Available_cavities_prior), sum_Null_new_nests_mean = sum(Null_new_nests_mean)) 

P1_meg <- P1_meg %>% 
  group_by(Trapnest, Treatment) %>% 
  summarise(Prop_new_of_avail_obs = (sum_New_nests_meg/sum_Available_cavities_prior), Prop_new_of_avail_null = (sum_Null_new_nests_mean/sum_Available_cavities_prior))

# pivot longer
P1_meg <- P1_meg %>% 
  pivot_longer(
    cols = c('Prop_new_of_avail_obs', 'Prop_new_of_avail_null'),
    names_to = 'Data_type',
    values_to = 'Proportion'
  )

# make the mean and error bars
P1_meg_sum <- P1_meg %>%
  group_by(Treatment, Data_type) %>%
  summarise(
    Mean = mean(Proportion),
    SD = sd(Proportion),
    SE = SD / sqrt(n()),
    CI_low = Mean - 1.96 * SE,
    CI_high = Mean + 1.96 * SE,
    .groups = 'drop'
  )

Fig_p1_meg <- P1_meg_sum %>%
  ggplot(aes(y = Mean, x = Treatment, fill = Data_type)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  geom_errorbar(aes(ymin = Mean - SE, ymax = Mean + SE),
                width = 0.3,
                position = position_dodge(width = 0.9)) +
  scale_fill_manual(
    values = c('Prop_new_of_avail_null' = '#F0C282',
      'Prop_new_of_avail_obs'  = '#B6686B'),
    name = bquote(italic(Megachile) ~ 'Data'),
    breaks = c('Prop_new_of_avail_null', 'Prop_new_of_avail_obs'),
    labels = c('Simulated', 'Observed')
  ) +
  labs(y = NULL, x = NULL)


## Combine figures 

# combine and add letters to each panel
combined_p1 <-  Fig_p1_os | Fig_p1_meg + theme(legend.box = 'vertical',
      legend.position = 'right') 
combined_p1 <- combined_p1 +
  plot_annotation(tag_levels = "A")

# make lengends stack ontop of each other
combined_p1 <- combined_p1 + plot_layout(guides = 'collect') &
  theme(legend.box = 'vertical') 

Fig_p1 <- combined_p1 +
  theme(plot.margin = margin(5, 5, 5, 5)) 

P1_left_label <- ggplot() +
  annotate('text',
           x = 0.5, y = 0.5,
           label = 'Proportion of new nests built in available cavities',
           angle = 90,
           size = 5) +
  theme_void() +
  theme(
    panel.background  = element_rect(fill = 'white', colour = NA),
    plot.background   = element_rect(fill = 'white', colour = NA),
    plot.margin       = margin(0, 0, 0, 0)
  )

P1_bottom_label <- ggplot() +
    annotate('text',
           x = 0.5, y = 0.5,
           label = 'Occupant density treatment',
           angle = 0,
           size = 5) +
  theme_void() +
  theme(
    panel.background  = element_rect(fill = 'white', colour = NA),
    plot.background   = element_rect(fill = 'white', colour = NA),
    plot.margin       = margin(0, 0, 0, 0)
  )

# combine them into a single plot object
Fig_p1 <- cowplot::plot_grid(P1_left_label, Fig_p1, ncol = 2, rel_widths = c(0.05, 0.95))
Fig_p1 <- cowplot::plot_grid(Fig_p1, P1_bottom_label, ncol = 1, rel_heights = c(1, 0.09))

# save
ggsave('Figures/Fig_p1.png', Fig_p1, width = 10, height = 5, dpi = 300)

# sample size
sum(trapnesting_os_null$New_nests_os) # 161
sum(trapnesting_meg_null$New_nests_meg) # 137


## Congenerics as continuous variable 
# so many zeros that weight it down 

# # make proportion of new nests / available cavities
# x_Prop_data_os <- trapnesting_os_null %>%
#   select(Trapnest, Treatment, Date, New_nests_os, Available_cavities_prior, Osmia_ps_prior, Null_new_nests_mean) %>%
#   group_by(Trapnest, Treatment, Date, Osmia_ps_prior) %>%
#   summarise(Prop_new_of_avail_obs = (New_nests_os/Available_cavities_prior), Prop_new_of_avail_null = (Null_new_nests_mean/Available_cavities_prior))
# 
# # pivot longer
# x_Prop_data_os <- x_Prop_data_os %>%
#   pivot_longer(
#     cols = c('Prop_new_of_avail_obs', 'Prop_new_of_avail_null'),
#     names_to = 'Data_type',
#     values_to = 'Proportion'
#   )
# 
# 
# x_Prop_data_os %>%
#   ggplot(aes(y = Proportion, x = Osmia_ps_prior, color = Data_type)) +
#   geom_jitter() +
#   geom_smooth(method = loess) 



```

## Parasite Attraction

```{r P2_Parasite_Attraction, echo=FALSE, warning=FALSE, message=FALSE}


## Osmia ##

# number of parasitized nests
P2_os <- nesting_cells_os %>% 
  select(Treatment, Trapnest, Nest_ID, Nest_parasitized) %>% 
  arrange(Nest_parasitized, Nest_ID) %>% 
  group_by(Nest_ID) %>% 
  slice_tail(n = 1) %>% 
  ungroup()

# count totals
P2_os_sum <- P2_os %>%
  count(Treatment, Trapnest, Nest_parasitized)

# create mean and error bars
P2_os_sum <- P2_os_sum %>%
  group_by(Treatment, Nest_parasitized) %>%
  summarise(
    Mean = mean(n),
    SD = sd(n),
    SE = SD / sqrt(n()),
    CI_low = Mean - 1.96 * SE,
    CI_high = Mean + 1.96 * SE,
    .groups = 'drop'
  )

# plot
Fig_p2_os <- P2_os_sum %>% 
  filter(Nest_parasitized == 'parasitized') %>% 
  ggplot(aes(y = Mean, x = Treatment)) + 
  geom_bar(position = 'dodge', stat = 'identity', fill = '#59989e') +
  geom_errorbar(
    aes(ymin = Mean - SE, ymax = Mean + SE),
    width = 0.3,
    position = position_dodge(width = 0.8)) +
  labs(y = NULL, x = NULL) + 
  scale_y_continuous(
    breaks = 0:4,
    limits = c(0, 4),
    labels = 0:4
  ) 
  

## Megachile ##

# number of parasitized nests
P2_meg <- nesting_cells_meg %>% 
  select(Treatment, Trapnest, Nest_ID, Nest_parasitized) %>% 
  arrange(Nest_parasitized, Nest_ID) %>% 
  group_by(Nest_ID) %>% 
  slice_tail(n = 1) %>% 
  ungroup()

# count totals
P2_meg_sum <- P2_meg %>%
  count(Treatment, Trapnest, Nest_parasitized)

# create mean and error bars
P2_meg_sum <- P2_meg_sum %>%
  group_by(Treatment, Nest_parasitized) %>%
  summarise(
    Mean = mean(n),
    SD = sd(n),
    SE = SD / sqrt(n()),
    CI_low = Mean - 1.96 * SE,
    CI_high = Mean + 1.96 * SE,
    .groups = 'drop'
  )

# plot
Fig_p2_meg <- P2_meg_sum %>% 
  filter(Nest_parasitized == 'parasitized') %>% 
  ggplot(aes(y = Mean, x = Treatment)) + 
  geom_bar(position='dodge', stat='identity', fill = '#B6686B') +
  geom_errorbar(
    aes(ymin = Mean - SE, ymax = Mean + SE),
    width = 0.3,
    position = position_dodge(width = 0.8)) +
  labs(y = NULL, x = NULL) +
  scale_y_continuous(
    breaks = 0:2,
    limits = c(0, 2),
    labels = 0:2
  ) 


## Combine plots


combined_p2 <-  Fig_p2_os | Fig_p2_meg 
combined_p2 <- combined_p2 +
  plot_annotation(tag_levels = "A")

Fig_p2 <- combined_p2 + plot_annotation(tag_levels = NULL) &
  theme(plot.margin = margin(5, 5, 5, 5)) 

P2_left_label <- ggplot() +
  annotate('text',
           x = 0.5, y = 0.5,
           label = 'Average number of parasitized nests',
           angle = 90,
           size = 5) +
  theme_void() +
  theme(
    panel.background  = element_rect(fill = 'white', colour = NA),
    plot.background   = element_rect(fill = 'white', colour = NA),
    plot.margin       = margin(0, 0, 0, 0)
  )

P2_bottom_label <- ggplot() +
    annotate('text',
           x = 0.5, y = 0.5,
           label = 'Occupant density treatment',
           angle = 0,
           size = 5) +
  theme_void() +
  theme(
    panel.background  = element_rect(fill = 'white', colour = NA),
    plot.background   = element_rect(fill = 'white', colour = NA),
    plot.margin       = margin(0, 0, 0, 0)
  )
  
# add left and bottom labels
Fig_p2 <- cowplot::plot_grid(P2_left_label, combined_p2, ncol = 2, rel_widths = c(0.05, 0.95)) 
Fig_p2 <- cowplot::plot_grid(Fig_p2, P2_bottom_label, ncol = 1, rel_heights = c(1, 0.09))


# save
ggsave('Figures/Fig_p2.png', Fig_p2, width = 8, height = 4, dpi = 300)


# sample size
table(P2_os$Nest_parasitized) # 27 no, 54 yes
table(P2_meg$Nest_parasitized) # 43 no, 13 yes

nesting_cells_os %>% 
  filter(Cell_occupant == 'parasite') %>% 
  count(Species_or_subtype, Nest_ID)
# sapyga: 52 / (54 + 75) = 40% 
# melittobia: 2 / (54 + 75) = 1.5%
nesting_cells_meg %>% 
  filter(Cell_occupant == 'parasite') %>% 
  count(Species_or_subtype, Nest_ID)
# chalcid: 3 / (92 + 13) = 2.9%
# coelioxys: 5 / (92 + 13) = 4.8%
# meloidae: 3 / (92 + 13) = 2.9%
# melittobia: 2 / (92 + 13) = 1.9%


```

## Parasite Avoidance

```{r P3a_Parasite_Avoidance, echo=FALSE, warning=FALSE, message=FALSE}


## Osmia ##

P3a_os <- trapnesting_os_null %>% 
  ggplot(aes(y = New_nests_os, x = DP_os_prior)) +
  geom_jitter(height = 0.09, width = 0.09, alpha = 0.4, color = '#59989e', shape = 16) +
  geom_smooth(method = 'lm', color = '#59989e', fill = '#59989e') +
  scale_y_continuous(
    breaks = 0:5,
    limits = c(0, 5.5),
    labels = 0:5
  )  +
  labs(y = NULL, x = NULL)
  

## Megachile ##

P3a_meg <- trapnesting_meg_null %>% 
  ggplot(aes(y = New_nests_meg, x = DP_meg_prior)) +
  geom_jitter(height = 0.09, width = 0.09, alpha = 0.4, color = '#B6686B', shape = 16) +
  geom_smooth(method = 'lm',  color = '#B6686B', fill = '#B6686B') +
  scale_x_continuous(breaks = 0:2, labels = 0:2) +
  scale_y_continuous(
    breaks = 0:5,
    limits = c(0, 5.5),
    labels = 0:5
  )  +
  labs(y = NULL, x = NULL)


# Combine 
        
combined_p3a <- P3a_os + P3a_meg + 
  plot_layout(ncol = 2, widths = c(4, 3), guides = 'collect') +
  plot_annotation(tag_levels = "A")
combined_p3a 

# make labels, needs white background so it's not png
P3a_left_label <- ggplot() +
  annotate('text',
           x = 0.5, y = 0.5,
           label = 'Number of new nests',
           angle = 90,
           size = 5) +
  theme_void() +
  theme(
    panel.background  = element_rect(fill = 'white', colour = NA),
    plot.background   = element_rect(fill = 'white', colour = NA),
    plot.margin       = margin(0, 0, 0, 0)
  ) 
P3a_bottom_label <- ggplot() +
    annotate('text',
           x = 0.5, y = 0.5,
           label = 'Number of neighbouring nests with detectable parasites',
           angle = 0,
           size = 5) +
  theme_void() +
  theme(
    panel.background  = element_rect(fill = 'white', colour = NA),
    plot.background   = element_rect(fill = 'white', colour = NA),
    plot.margin       = margin(0, 0, 0, 0)
  )
  
# add left and bottom labels
Fig_p3a <- cowplot::plot_grid(P3a_left_label, combined_p3a, ncol = 2, rel_widths = c(0.05, 0.95))
Fig_p3a <- cowplot::plot_grid(Fig_p3a, P3a_bottom_label, ncol = 1, rel_heights = c(1, 0.06))

# save
ggsave('Figures/Fig_p3a.png', Fig_p3a, width = 8, height = 4, dpi = 300) 


```

```{r P3b_Investment, echo=FALSE, warning=FALSE, message=FALSE}

## Osmia ##

# make proportion data for figure
nesting_investment_os <- nesting_investment_os %>% mutate(Prop_filled = Filled_length / Straw_length)

# plot
P3b_os <- nesting_investment_os %>%
  filter(!is.na(Nest_parasitized)) %>%
  ggplot(aes(DP_os_prior, Prop_filled, fill = Nest_parasitized)) +
  geom_smooth(method = 'glm',
    method.args = list(family = binomial()),
    aes(colour = Nest_parasitized)) +
  geom_jitter(aes(colour = Nest_parasitized), 
    alpha = 0.7, width = 0.05, height = 0.01, shape = 16) +
  scale_colour_manual(values = c('#59989e', '#21393b'),
    labels = c('Not parasitized', 'Parasitized'),
    name = bquote(italic(Osmia) ~ 'nests')) +
  scale_fill_manual(values = c('#59989e', '#21393b'), 
                    labels = c('Not parasitized', 'Parasitized'), 
                    name = bquote(italic(Osmia) ~ 'nests')) +
  labs(y = NULL, x = NULL) + 
  ylim(0, 1.05)


## Megachile ##

# put 'not parasitized' last so it is drawn on top and make proportion data for figure
nesting_investment_meg <- nesting_investment_meg %>%
  mutate(Nest_parasitized = factor(Nest_parasitized, levels = c('parasitized', 'not parasitized')),
         Prop_filled = Filled_length / Straw_length)

# plot 
P3b_meg <- nesting_investment_meg %>%
  filter(!is.na(Nest_parasitized)) %>%
  ggplot(aes(DP_meg_prior, Prop_filled, fill = Nest_parasitized, colour = Nest_parasitized)) +
  geom_smooth(method = 'glm', method.args = list(family = binomial())) +
  geom_jitter(alpha = 0.7, width = 0.1, height = 0.1, shape = 16) +
  scale_colour_manual(
    values = c('not parasitized' = '#B6686B', 'parasitized' = '#422426'),
    breaks = c('not parasitized', 'parasitized'),
    labels = c('Not parasitized', 'Parasitized'),
    name = bquote(italic(Megachile) ~ 'nests')
  ) +
  scale_fill_manual(
    values = c('not parasitized' = '#B6686B', 'parasitized' = '#422426'),
    breaks = c('not parasitized', 'parasitized'),
    labels = c('Not parasitized', 'Parasitized'),
    name = bquote(italic(Megachile) ~ 'nests')
  ) +
  labs(y = NULL, x = NULL) +
  ylim(0, 1.05) +
  scale_x_continuous(breaks = c(0, 1), labels = c('0', '1')) 



# Combine 
        
combined_p3b <- P3b_os + P3b_meg + plot_layout(ncol = 2, widths = c(4, 3), guides = 'collect') 
combined_p3b <- combined_p3b +
  plot_annotation(tag_levels = "A")

P3b_left_label <- ggplot() +
  annotate('text',
           x = 0.5, y = 0.5,
           label = 'Proportion of nest filled with cells',
           angle = 90,
           size = 5) +
  theme_void() +
  theme(
    panel.background  = element_rect(fill = 'white', colour = NA),
    plot.background   = element_rect(fill = 'white', colour = NA),
    plot.margin       = margin(0, 0, 0, 0)
  ) 

P3b_bottom_label <- ggplot() +
    annotate('text',
           x = 0.5, y = 0.5,
           label = 'Number of neighbouring nests with detectable parasites',
           angle = 0,
           size = 5) +
  theme_void() +
  theme(
    panel.background  = element_rect(fill = 'white', colour = NA),
    plot.background   = element_rect(fill = 'white', colour = NA),
    plot.margin       = margin(0, 0, 0, 0)
  )
  
# add left and bottom labels
Fig_p3b <- cowplot::plot_grid(P3b_left_label, combined_p3b, ncol = 2, rel_widths = c(0.05, 0.95)) 
Fig_p3b <- cowplot::plot_grid(Fig_p3b, P3b_bottom_label, ncol = 1, rel_heights = c(1, 0.09))

# save
ggsave('Figures/Fig_p3b.png', Fig_p3b, width = 11, height = 5, dpi = 300) 


```

Nest Termination

```{r P3c_Nest_Termination,echo=FALSE, warning=FALSE, message=FALSE}

## Osmia ##

nesting_cells_os_fig <- nesting_cells_os %>% select(Nest_ID, Cell_ID, Cell_position, Cell_parasitized) 

nesting_cells_os_fig <- nesting_cells_os_fig %>% 
  mutate(Cell_parasitized_word = ifelse(Cell_parasitized == 1, 'Parasitized', 'Not parasitized'))

Fig_p3c_os <- nesting_cells_os_fig %>% 
  filter(Cell_position == 'last cell' | Cell_position == 'not last cell') %>% 
  ggplot(aes(x = Cell_position, fill = Cell_parasitized_word, group = Cell_parasitized_word)) +
  geom_bar(position = 'fill') +
  scale_fill_manual(
    values = c('Not parasitized' = '#59989e', 'Parasitized' = '#21393b'),
    name = bquote(italic(Osmia) ~ 'nests')
  ) +
  labs(y = NULL, x = NULL)


## Megachile ##

nesting_cells_meg_fig <- nesting_cells_meg %>% select(Nest_ID, Cell_ID, Cell_position, Cell_parasitized)

nesting_cells_meg_fig <- nesting_cells_meg_fig %>% 
  mutate(Cell_parasitized_word = ifelse(Cell_parasitized == 1, 'Parasitized', 'Not parasitized'))

Fig_p3c_meg <- nesting_cells_meg_fig %>% 
  filter(Cell_position == 'last cell' | Cell_position == 'not last cell') %>% 
  ggplot(aes(x = Cell_position, fill = Cell_parasitized_word, group = Cell_parasitized_word)) +
  geom_bar(position = 'fill') +
  scale_fill_manual(
    values = c('Not parasitized' = '#B6686B', 'Parasitized' = '#422426'),
    name = bquote(italic(Megachile) ~ 'nests')
  ) +
  labs(y = NULL, x = NULL)
 


## Combine plots

combined_p3c <-  Fig_p3c_os | Fig_p3c_meg

combined_p3c <- combined_p3c +
  plot_annotation(tag_levels = "A")

# make lengends stack ontop of each other
combined_p3c <- combined_p3c + plot_layout(guides = 'collect') &
  theme(legend.box = 'vertical') 

Fig_p3c <- combined_p3c + plot_annotation(tag_levels = NULL) &
  theme(plot.margin = margin(5, 5, 5, 5))

P3c_left_label <- ggplot() +
  annotate('text',
           x = 0.5, y = 0.5,
           label = 'Proportion of cells',
           angle = 90,
           size = 5) +
  theme_void() +
  theme(
    panel.background  = element_rect(fill = 'white', colour = NA),
    plot.background   = element_rect(fill = 'white', colour = NA),
    plot.margin       = margin(0, 0, 0, 0)
  )

P3c_bottom_label <- ggplot() +
    annotate('text',
           x = 0.5, y = 0.5,
           label = 'Cell position',
           angle = 0,
           size = 5) +
  theme_void() +
  theme(
    panel.background  = element_rect(fill = 'white', colour = NA),
    plot.background   = element_rect(fill = 'white', colour = NA),
    plot.margin       = margin(0, 0, 0, 0)
  )
  
# add left and bottom labels
Fig_p3c <- cowplot::plot_grid(P3c_left_label, combined_p3c, ncol = 2, rel_widths = c(0.05, 0.95)) 
Fig_p3c <- cowplot::plot_grid(Fig_p3c, P3c_bottom_label, ncol = 1, rel_heights = c(1, 0.09))

# save
ggsave('Figures/Fig_p3c.png', Fig_p3c, width = 10, height = 5, dpi = 300) 


```

```{r Supplementary_figures}


## Graph active Osmia mothers and parasites

# number of parasitized nests
act_moms_os <- nesting_cells_os %>% 
  select(Treatment, Trapnest, Nest_ID, Nest_parasitized, Cell_parasitized, Osmia_active_mothers) 

# mutate the cell_parasitized column to words 
act_moms_os <- act_moms_os %>% mutate(Cell_parasitized_word = ifelse(Cell_parasitized == 1, 'Parasitized',
                                                      ifelse(Cell_parasitized == 0, 'Not parasitized', NA)))

Sup_fig_2aiii <- act_moms_os %>% 
  ggplot(aes(Osmia_active_mothers, fill = Cell_parasitized_word)) +
  geom_histogram(position = 'dodge', binwidth = 0.5) +
  scale_fill_manual(
    values = c('Not parasitized' = '#59989e', 'Parasitized' = '#21393b'),
    name = bquote(italic(Osmia) ~ 'cell status')) +
labs(
  y = 'Number of cells',
  x = bquote('Active ' * italic(Osmia) * ' mothers')
)

# save
ggsave('Figures/Sup_fig_2aiii.png', Sup_fig_2aiii, width = 6, height = 4, dpi = 300) 



## Graph Megachile interaction with DP and NDP with plots from the models 

# tried running a model on the average of null new nests to plot it, but the average wasn't integers and it broke R :/
# so then i round to the nearest integer, but it's very small, and rounds down to 0 so causes me to lose like 20% of the nests 
# instead, I'll graph 5 random null columns
sample(1:100, 5, replace = TRUE)
# 10 82 25 27 42

# make models
# 10
mod_3aiii_sim_1 <- glmer(Null_new_nests10 ~ scale(DP_meg_prior) * scale(NDP_ps_meg_prior) + scale(Good_days) + poly(Day_of_year,2) + Year + Site + (1|Subsite/Trapnest), data = trapnesting_meg_null, family = poisson)
# 82
mod_3aiii_sim_2 <- glmer(Null_new_nests82 ~ scale(DP_meg_prior) * scale(NDP_ps_meg_prior) + scale(Good_days) + poly(Day_of_year,2) + Year + Site + (1|Subsite/Trapnest), data = trapnesting_meg_null, family = poisson)
# 25
mod_3aiii_sim_3 <- glmer(Null_new_nests25 ~ scale(DP_meg_prior) * scale(NDP_ps_meg_prior) + scale(Good_days) + poly(Day_of_year,2) + Year + Site + (1|Subsite/Trapnest), data = trapnesting_meg_null, family = poisson)
# 27
mod_3aiii_sim_4 <- glmer(Null_new_nests27 ~ scale(DP_meg_prior) * scale(NDP_ps_meg_prior) + scale(Good_days) + poly(Day_of_year,2) + Year + Site + (1|Subsite/Trapnest), data = trapnesting_meg_null, family = poisson)
# 42
mod_3aiii_sim_5 <- glmer(Null_new_nests5 ~ scale(DP_meg_prior) * scale(NDP_ps_meg_prior) + scale(Good_days) + poly(Day_of_year,2) + Year + Site + (1|Subsite/Trapnest), data = trapnesting_meg_null, family = poisson)


# make with ggplot to save
Df_mod_3aiii_sim_1 <- ggpredict(mod_3aiii_sim_1, terms = c('NDP_ps_meg_prior [all]', 'DP_meg_prior'))

Sup_fig_3aiii_sim_1 <- ggplot(Df_mod_3aiii_sim_1, aes(x = x, y = predicted, color = group)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = group),
              alpha = 0.15, color = NA) +
  labs(
    x = NULL,
    y = NULL,
    color = 'Simulated number of neighbouring\nnests with detectable parasites',
    fill = 'Simulated number of neighbouring\nnests with detectable parasites'
  ) +
  scale_color_manual(values = c(
  'goldenrod1',
  'goldenrod3',
  '#705410'
  )) +
  scale_fill_manual(values = c(
  'goldenrod1',
  'goldenrod3',
  '#705410'
  )) +
  theme(
    legend.position = "top",
    legend.justification = "center",
    legend.box.just = "center"
  )

Df_mod_3aiii_sim_2 <- ggpredict(mod_3aiii_sim_2, terms = c('NDP_ps_meg_prior [all]', 'DP_meg_prior'))

Sup_fig_3aiii_sim_2 <- ggplot(Df_mod_3aiii_sim_2, aes(x = x, y = predicted, color = group)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = group),
              alpha = 0.15, color = NA) +
  labs(
    x = NULL,
    y = NULL,
  ) +
  scale_color_manual(values = c(
  'goldenrod1',
  'goldenrod3',
  '#705410'
  )) +
  scale_fill_manual(values = c(
  'goldenrod1',
  'goldenrod3',
  '#705410'
  )) 

# simulation 3
Df_mod_3aiii_sim_3 <- ggpredict(mod_3aiii_sim_3, terms = c('NDP_ps_meg_prior [all]', 'DP_meg_prior'))

Sup_fig_3aiii_sim_3 <- ggplot(Df_mod_3aiii_sim_3, aes(x = x, y = predicted, color = group)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = group),
              alpha = 0.15, color = NA) +
  labs(
    x = NULL,
    y = NULL,
  ) +
  scale_color_manual(values = c(
  'goldenrod1',
  'goldenrod3',
  '#705410'
  )) +
  scale_fill_manual(values = c(
  'goldenrod1',
  'goldenrod3',
  '#705410'
  )) 

# simulation 4
Df_mod_3aiii_sim_4 <- ggpredict(mod_3aiii_sim_4, terms = c('NDP_ps_meg_prior [all]', 'DP_meg_prior'))

Sup_fig_3aiii_sim_4 <- ggplot(Df_mod_3aiii_sim_4, aes(x = x, y = predicted, color = group)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = group),
              alpha = 0.15, color = NA) +
  labs(
    x = NULL,
    y = NULL,
  ) +
  scale_color_manual(values = c(
  'goldenrod1',
  'goldenrod3',
  '#705410'
  )) +
  scale_fill_manual(values = c(
  'goldenrod1',
  'goldenrod3',
  '#705410'
  )) 

# simulation 5
Df_mod_3aiii_sim_5 <- ggpredict(
  mod_3aiii_sim_5,
  terms = c('NDP_ps_meg_prior [all]', 'DP_meg_prior')
)

Sup_fig_3aiii_sim_5 <- ggplot(Df_mod_3aiii_sim_5, aes(x = x, y = predicted, color = group)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = group),
              alpha = 0.15, color = NA) +
  labs(
    x = NULL,
    y = NULL,
  ) +
  scale_color_manual(values = c(
  'goldenrod1',
  'goldenrod3',
  '#705410'
  )) +
  scale_fill_manual(values = c(
  'goldenrod1',
  'goldenrod3',
  '#705410'
  )) 


# observed 

Df_mod_3aiii_obs <- ggpredict(mod_3aiii_choice_consp_par_meg_ps, terms = c('NDP_ps_meg_prior [all]', 'DP_meg_prior'))

Sup_fig_3aiii_obs <- ggplot(Df_mod_3aiii_obs, aes(x = x, y = predicted, color = group)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = group),
              alpha = 0.15, color = NA) +
  labs(
    x = NULL,
    y = NULL,
    color = 'Observed number of neighbouring\nnests with detectable parasites',
    fill = 'Observed number of neighbouring\nnests with detectable parasites'
  ) +
  scale_color_manual(values = c(
  '#ebadb0',
  '#cd5155',
  '#813134'
  )) +
  scale_fill_manual(values = c(
  '#ebadb0',
  '#cd5155',
  '#813134'
  )) +
  theme(
    legend.position = "top",
    legend.justification = "center",
    legend.box.just = "center"
  )



## Combine plots

# make specials legends for A and B panels
Sup_fig_3aiii_obs <- Sup_fig_3aiii_obs +
  guides(
    colour = guide_legend(title.position = "top", label.position = "bottom", nrow = 1),
    fill   = guide_legend(title.position = "top", label.position = "bottom", nrow = 1)
  ) +
  theme(
    legend.position = "top",
    legend.justification = "center",
    legend.box.just = "center",
    legend.box = "vertical",
    legend.title = element_text(hjust = 0.5),
    legend.spacing.y = unit(2, "pt"),
    legend.margin = margin(b = -5)
  )

Sup_fig_3aiii_sim_1 <- Sup_fig_3aiii_sim_1 +
  guides(
    colour = guide_legend(title.position = "top", label.position = "bottom", nrow = 1),
    fill   = guide_legend(title.position = "top", label.position = "bottom", nrow = 1)
  ) +
  theme(
    legend.position = "top",
    legend.justification = "center",
    legend.box.just = "center",
    legend.box = "vertical",
    legend.title = element_text(hjust = 0.5),
    legend.spacing.y = unit(2, "pt"),
    legend.margin = margin(b = -5)
  )

# remove legends from other panels
Sup_fig_3aiii_sim_2 <- Sup_fig_3aiii_sim_2 + theme(legend.position = "none")
Sup_fig_3aiii_sim_3 <- Sup_fig_3aiii_sim_3 + theme(legend.position = "none")
Sup_fig_3aiii_sim_4 <- Sup_fig_3aiii_sim_4 + theme(legend.position = "none")
Sup_fig_3aiii_sim_5 <- Sup_fig_3aiii_sim_5 + theme(legend.position = "none")

# combine all
# Combined_p3a_sup <- (Sup_fig_3aiii_obs + Sup_fig_3aiii_sim_1) /
#                (Sup_fig_3aiii_sim_2 + Sup_fig_3aiii_sim_3) /
#                (Sup_fig_3aiii_sim_4 + Sup_fig_3aiii_sim_5) +
#   plot_annotation(tag_levels = "A")

Combined_p3a_sup <- (Sup_fig_3aiii_obs + Sup_fig_3aiii_sim_1) /
                    (Sup_fig_3aiii_sim_2 + Sup_fig_3aiii_sim_3) /
                    (Sup_fig_3aiii_sim_4 + Sup_fig_3aiii_sim_5) 

# make labels
P3a_sup_left_label <- ggplot() +
  annotate('text',
           x = 0.5, y = 0.5,
           label = 'Predicted probability of new nests',
           angle = 90,
           size = 5) +
  theme_void() +
  theme(
    panel.background  = element_rect(fill = 'white', colour = NA),
    plot.background   = element_rect(fill = 'white', colour = NA),
    plot.margin       = margin(0, 0, 0, 0)
  )

P3a_sup_bottom_label <- ggdraw() + # diff than other labels so I can move it to the left
  draw_label(
    "Number of neighbouring nests with no detectable parasites",
    x = 0.5,  
    y = 0.8,
    hjust = 0.5,
    vjust = 0) +
  theme(
    panel.background  = element_rect(fill = 'white', colour = NA),
    plot.background   = element_rect(fill = 'white', colour = NA),
    plot.margin       = margin(0, 0, 0, 0)
  )
  
# add left and bottom labels
Sup_fig_3aiii <- cowplot::plot_grid(P3a_sup_left_label, Combined_p3a_sup, ncol = 2, rel_widths = c(0.05, 0.95)) 
Sup_fig_3aiii <- cowplot::plot_grid(Sup_fig_3aiii, P3a_sup_bottom_label, ncol = 1, rel_heights = c(1, 0.03)) 


Sup_fig_3aiii

# save
ggsave('Figures/Sup_fig_3aiii.png', Sup_fig_3aiii, width = 10, height = 12, dpi = 900) 






```
