---
title: "Figures"
format: html
editor: visual
---

In total, I have 164 osmia nests and 58 megachile nests (IDed based on nesting material).

```{r Getting things ready, include=FALSE}

library(ggplot2)
library(ggeffects)
library(tidyverse)
library(kableExtra)
library(lme4)

# If not loaded already:
nesting <- read_csv('data/nesting_cleaned_all_bees.csv')
nesting_os <- read_csv('data/nesting_cleaned_osmia.csv')
nesting_meg <- read_csv('data/nesting_cleaned_megachile.csv')
investment <- read_csv('data/investment_cleaned.csv')
obs.os <- read_csv('data/observed_data_os.csv')
obs.meg <- read_csv('data/observed_data_meg.csv')
exp.os <- read_csv('data/expected_data_os.csv')
exp.meg <- read_csv('data/expected_data_meg.csv')

# remove numbers columns to chi data 
obs.os <- obs.os %>% select(Site, Low, Mid, High)
obs.meg <- obs.meg %>% select(Site, Low, Mid, High)
exp.os <- exp.os %>% select(Site, Low, Mid, High)
exp.meg <- exp.meg %>% select(Site, Low, Mid, High)


theme_set(theme_classic(base_size=12)) 

# number of nests
nesting_os %>% filter(!is.na(Bee_choice)) %>% 
  summarize(nests_total = sum(Bee_choice)) # 164 osmia nests for osmia through the summer
nesting_meg %>% filter(!is.na(Bee_choice)) %>% 
  summarize(nests_total = sum(Bee_choice)) # 58 megachile nests for osmia through the summer


# model that isn't overdispersed that I can show
mod_choice_cav_os <- glmer(Bee_choice ~ Available_prior + Good_days + Day_of_year + Site + (1|Subsite/Trapnest/Cavity_ID), data = nesting_os, family = binomial) # boundary singular warning


```

## Nesting per Available Cavities

```{r Nest per Available Cavities, echo=FALSE, warning=FALSE, message=FALSE}


### Osmia 

nesting_os %>% 
  ggplot(aes(Available_prior, Bee_choice)) + 
  geom_jitter(height = 0.05, alpha = 0.5, aes(colour = Occupant)) +
  stat_smooth(method='glm', method.args=list(family='binomial'), colour = 'grey75') +
  scale_color_manual(values=c('steelblue3', 'plum3')) +
  labs(x='Available cavities', y = 'Presence of Presence of new nest for each visit') +
  theme( # removing the y axes labels
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()) + 
  xlim(0, 18)

# only model that isn't overdispered rn
ggpredict(mod_choice_cav_os, c('Available_prior')) %>% plot(rawdata = TRUE, jitter = .04) + labs(x = 'Available cavities', y = 'Presence of new nest for each visit', title = 'Plotted model for Osmia')

### Megachile 

nesting_meg %>% 
  ggplot(aes(Available_prior, Bee_choice)) + 
  geom_jitter(height = 0.05, alpha = 0.5, aes(colour = Occupant)) +
  stat_smooth(method='glm', method.args=list(family='binomial'), colour = 'grey75') +
  scale_color_manual(values=c('darkgoldenrod2', 'steelblue3')) +
  labs(x='Available cavities', y = 'Presence of Presence of new nest for each visit') +
  theme(# removing the y axes labels
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()) + 
  xlim(0, 18)


```

## Nesting per Conspecific Presence (with and without pseudo nests)

```{r Conspecific Presence, echo=FALSE, warning=FALSE, message=FALSE}


# Osmia # with pseudo 
nesting_os %>% 
  ggplot(aes(Osmia_ps_prior, Bee_choice)) + 
  geom_jitter(height = 0.05, alpha = 0.6, aes(colour = Occupant)) + 
  stat_smooth(method='glm', method.args=list(family='binomial'), colour = 'grey75') +
  labs(x = 'Osmia occupancies (including pseudo)', y = 'Presence of new nest for each visit') +
  scale_color_manual(values=c('steelblue3', 'plum3'))  +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()) +
  xlim(0, 18)




# Osmia # without pseudo 
nesting_os %>% 
  ggplot(aes(Osmia_no_ps_prior, Bee_choice)) + 
  geom_jitter(height = 0.05, alpha = 0.6, aes(colour = Occupant)) + 
  stat_smooth(method='glm', method.args=list(family='binomial'), colour = 'grey75') +
  labs(x = 'Osmia occupancies (excluding pseudo)', y = 'Presence of new nest for each visit') +
  scale_color_manual(values=c('steelblue3', 'plum3')) +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()) +
  xlim(0, 18)


### Megachile with pseudo 

nesting_meg %>% 
  ggplot(aes(Meg_ps_prior, Bee_choice)) + 
  geom_jitter(height = 0.05, alpha = 0.6, aes(colour = Occupant)) + 
  stat_smooth(method='glm', method.args=list(family='binomial')) +
  labs(x = 'Megachile occupancies (including pseudo)', y = 'Presence of new nest for each visit') +
  scale_color_manual(values=c('darkgoldenrod2', 'steelblue3')) +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()) +
  xlim(0, 18)


### Megachile without pseudo 

nesting_meg %>% 
  ggplot(aes(Meg_no_ps_prior, Bee_choice)) + 
  geom_jitter(height = 0.05, alpha = 0.6, aes(colour = Occupant)) + 
  stat_smooth(method='glm', method.args=list(family='binomial'), colour = 'grey75') +
  labs(x = 'Megachile occupancies (excluding pseudo)', y = 'Presence of new nest for each visit') +
  scale_color_manual(values=c('darkgoldenrod2', 'steelblue3')) +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()) +
  xlim(0, 18)


```

## Tables


```{r Chi Square Tables: on-season, echo = FALSE}

### Only on-season data

knitr::kable(exp.os, 
             caption = 'Table 1. Expected new nests: Osmia',
             col.names = c('Site', 'Low', 'Mid', 'High')) %>% 
  kable_styling()

knitr::kable(obs.os, 
             caption = 'Table 2. Observed new nests: Osmia',
             col.names = c('Site', 'Low', 'Mid', 'High')) %>% 
  kable_styling()

knitr::kable(exp.meg, 
             caption = 'Table 3. Expected new nests: Megachile',
             col.names = c('Site', 'Low', 'Mid', 'High')) %>% 
  kable_styling()

knitr::kable(obs.meg, 
             caption = 'Table 4. Observed new nests: Megachile',
             col.names = c('Site', 'Low', 'Mid', 'High')) %>% 
  kable_styling()

```


## Parasitism

```{r Parasitism, echo=FALSE, warning=FALSE, message=FALSE}


# each data point is again a trapnest and date combo


# New nests against parasites in the trapnest

nesting_os %>% 
  ggplot(aes(Par_in_trapnest, Bee_choice)) + 
  stat_smooth(method='glm', colour = 'hotpink2', fill = 'hotpink2') +
  geom_jitter(height = 0.03, alpha = 0.4) + 
  labs(title = 'New nests vs parasites in the trapnest')


# Cumulative number of parasites per osmia occupancies

nesting_os %>% 
  filter(!is.na(Cumulative_par)) %>% 
  ggplot(aes(Osmia_no_ps_prior, Cumulative_par)) + 
  geom_jitter(height = 0.05, alpha = 0.6) + 
  stat_smooth(method='glm', colour = 'coral2', fill = 'coral2') +
  labs(x = 'Osmia occupancies (excluding pseudo)', y = 'Cumulative number of parasites', title = 'Cumulative number of parasites per osmia occupancies (excluding pseudo)') 

nesting_os %>% # with peusdo 
  filter(!is.na(Cumulative_par)) %>% 
  ggplot(aes(Osmia_ps_prior, Cumulative_par)) + 
  geom_jitter(height = 0.05, alpha = 0.6) + 
  stat_smooth(method='glm', colour = 'coral2', fill = 'coral2') +
  labs(x = 'Osmia occupancies (including pseudo)', y = 'Cumulative number of parasites', title = 'Cumulative number of parasites per osmia occupancies (including pseudo)') 


# Proportion of cells in a nest with parasites per osmia occupancies

nesting %>% 
  filter(Occupant == 'osmia' & !is.na(Prop_cells_par)) %>% 
  ggplot(aes(Osmia_no_ps_prior, Prop_cells_par)) +
  geom_jitter() + 
  stat_smooth(method='glm', method.args=list(family='binomial'), colour = 'plum', fill = 'plum') +
  labs(x = 'Osmia occupancies (excluding pseudo)', y = 'Proportion of cells in a nest that are parasitized', title = 'Proportion of cells in a nest with parasites per osmia occupancies (excluding pseudo)') 

nesting %>% # with peusdo 
  filter(Occupant == 'osmia' & !is.na(Prop_cells_par)) %>% 
  ggplot(aes(Osmia_ps_prior, Prop_cells_par)) +
  geom_jitter() + 
  stat_smooth(method='glm', method.args=list(family='binomial'), colour = 'plum', fill = 'plum') +
  labs(x = 'Osmia occupancies (including pseudo)', y = 'Proportion of cells in a nest that are parasitized', title = 'Proportion of cells in a nest with parasites per osmia occupancies (including pseudo)')


```

## Nest Investment

```{r Investment, echo=FALSE, warning=FALSE, message=FALSE}


investment_os <- investment %>% filter(Occupant == 'osmia')
investment_meg <- investment %>% filter(Occupant == 'megachile')


investment_os %>% 
  ggplot(aes(Prop_filled, Par_in_trapnest)) + 
  geom_jitter(height = 0, alpha = 0.4) + stat_smooth()



investment$Treatment <- factor(investment$Treatment, levels=c('Low', 'Mid', 'High'))


investment %>% filter(Occupant == 'osmia' | Occupant == 'megachile') %>% 
  ggplot(aes(Treatment, Prop_filled, fill = Occupant)) +
  geom_boxplot(alpha = 0.8) +
  scale_fill_manual(values=c('goldenrod2', 'plum3'), labels = c('Megachile', 'Osmia')) +
  labs(y = 'Proportion of straw filled with cells') + 
  theme(legend.text = element_text(face = 'italic'))



```

```{r Notes, include=FALSE}

# Notes 

# to change the colour of stat_smooth: stat_smooth(method='glm', colour = 'coral2', fill = 'coral2')

```
